
package com.dna.deposito;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "serviciodeposito", targetNamespace = "http://aduana.gov.py/webservices", wsdlLocation = "https://securetest.aduana.gov.py/sgd2/serviciodeposito?wsdl")
public class Serviciodeposito
    extends Service
{

    private final static URL SERVICIODEPOSITO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.dna.deposito.Serviciodeposito.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.dna.deposito.Serviciodeposito.class.getResource(".");
            url = new URL(baseUrl, "https://securetest.aduana.gov.py/sgd2/serviciodeposito?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://securetest.aduana.gov.py/sgd2/serviciodeposito?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICIODEPOSITO_WSDL_LOCATION = url;
    }

    public Serviciodeposito(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Serviciodeposito() {
        super(SERVICIODEPOSITO_WSDL_LOCATION, new QName("http://aduana.gov.py/webservices", "serviciodeposito"));
    }

    /**
     * 
     * @return
     *     returns ServiciodepositoSoap
     */
    @WebEndpoint(name = "serviciodepositoSoap")
    public ServiciodepositoSoap getServiciodepositoSoap() {
        return super.getPort(new QName("http://aduana.gov.py/webservices", "serviciodepositoSoap"), ServiciodepositoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciodepositoSoap
     */
    @WebEndpoint(name = "serviciodepositoSoap")
    public ServiciodepositoSoap getServiciodepositoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://aduana.gov.py/webservices", "serviciodepositoSoap"), ServiciodepositoSoap.class, features);
    }

}
