
package com.dna.deposito;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "serviciodepositoSoap", targetNamespace = "http://aduana.gov.py/webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciodepositoSoap {


    /**
     * 
     * @param autenticacion
     * @param despacho
     * @return
     *     returns com.dna.deposito.ExpedienteThRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarRetiroAnticipado", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.VerificarRetiroAnticipado")
    @ResponseWrapper(localName = "verificarRetiroAnticipadoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.VerificarRetiroAnticipadoResponse")
    public ExpedienteThRespuestaConsulta verificarRetiroAnticipado(
        @WebParam(name = "despacho", targetNamespace = "")
        String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.CouRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarGuiasCou", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarGuiasCou")
    @ResponseWrapper(localName = "consultarGuiasCouResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarGuiasCouResponse")
    public CouRespuestaConsulta consultarGuiasCou(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param sgtDta
     * @return
     *     returns com.dna.deposito.TransitoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transitoCambioEstado", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.TransitoCambioEstado")
    @ResponseWrapper(localName = "transitoCambioEstadoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.TransitoCambioEstadoResponse")
    public TransitoRespuestaConsulta transitoCambioEstado(
        @WebParam(name = "sgtDta", targetNamespace = "")
        SgtDta sgtDta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @param despacho
     * @param titulo
     * @param prefijo
     * @return
     *     returns com.dna.deposito.DespachoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDespacho", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDespacho")
    @ResponseWrapper(localName = "consultarDespachoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDespachoResponse")
    public DespachoRespuestaConsulta consultarDespacho(
        @WebParam(name = "despacho", targetNamespace = "")
        String despacho,
        @WebParam(name = "manifiesto", targetNamespace = "")
        String manifiesto,
        @WebParam(name = "prefijo", targetNamespace = "")
        String prefijo,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param nroDeclaracion
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.IngRemiEfcRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoRemiEfcConsultar", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoRemiEfcConsultar")
    @ResponseWrapper(localName = "ingresoRemiEfcConsultarResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoRemiEfcConsultarResponse")
    public IngRemiEfcRespuesta ingresoRemiEfcConsultar(
        @WebParam(name = "nroDeclaracion", targetNamespace = "")
        String nroDeclaracion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param idDeclaracionSimplificada
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracionSimplificadaExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplificadaExpo")
    @ResponseWrapper(localName = "consultarDeclaracionSimplificadaExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplificadaExpoResponse")
    public DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplificadaExpo(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param idDeclaracionSimplificada
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracionSimplificada", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplificada")
    @ResponseWrapper(localName = "consultarDeclaracionSimplificadaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplificadaResponse")
    public DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplificada(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param ruc
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.SaldoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSaldoRuc", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarSaldoRuc")
    @ResponseWrapper(localName = "consultarSaldoRucResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarSaldoRucResponse")
    public SaldoRespuestaConsulta consultarSaldoRuc(
        @WebParam(name = "ruc", targetNamespace = "")
        String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param rut
     * @param fechaHasta
     * @param aduanaOrigen
     * @param fechaDesde
     * @param abrevEstado
     * @param autenticacion
     * @param aduanaDestino
     * @return
     *     returns com.dna.deposito.TransitoRespuestaConsultaSqf
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTransitosSqf", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarTransitosSqf")
    @ResponseWrapper(localName = "consultarTransitosSqfResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarTransitosSqfResponse")
    public TransitoRespuestaConsultaSqf consultarTransitosSqf(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "rut", targetNamespace = "")
        String rut,
        @WebParam(name = "abrevEstado", targetNamespace = "")
        String abrevEstado,
        @WebParam(name = "aduanaOrigen", targetNamespace = "")
        String aduanaOrigen,
        @WebParam(name = "aduanaDestino", targetNamespace = "")
        String aduanaDestino,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param ruc
     * @param fechaIni
     * @param autenticacion
     * @param items
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaListaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaDeclaracionSimplGuia", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracionSimplGuia")
    @ResponseWrapper(localName = "consultarListaDeclaracionSimplGuiaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracionSimplGuiaResponse")
    public DeclaracionSimplificadaListaRespuestaConsulta consultarListaDeclaracionSimplGuia(
        @WebParam(name = "fechaIni", targetNamespace = "")
        String fechaIni,
        @WebParam(name = "items", targetNamespace = "")
        List<DeclaracionSimplificadaItem> items,
        @WebParam(name = "ruc", targetNamespace = "")
        String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param declaracion
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DespachoSimplTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoDespachoSimplExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDespachoSimplExpo")
    @ResponseWrapper(localName = "ingresoDespachoSimplExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDespachoSimplExpoResponse")
    public DespachoSimplTransaccion ingresoDespachoSimplExpo(
        @WebParam(name = "declaracion", targetNamespace = "")
        DeclaracionSimplificada declaracion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @param prefijoTitulo
     * @param tipoMovimiento
     * @param numeroTitulo
     * @return
     *     returns com.dna.deposito.ManifiestoTituloRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarManifiestoTitulo", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestoTitulo")
    @ResponseWrapper(localName = "consultarManifiestoTituloResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestoTituloResponse")
    public ManifiestoTituloRespuestaConsulta consultarManifiestoTitulo(
        @WebParam(name = "tipoMovimiento", targetNamespace = "")
        String tipoMovimiento,
        @WebParam(name = "numeroTitulo", targetNamespace = "")
        String numeroTitulo,
        @WebParam(name = "prefijoTitulo", targetNamespace = "")
        String prefijoTitulo,
        @WebParam(name = "manifiesto", targetNamespace = "")
        String manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param nroTraslado
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.TrasladosRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trasladosEfc", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.TrasladosEfc")
    @ResponseWrapper(localName = "trasladosEfcResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.TrasladosEfcResponse")
    public TrasladosRespuestaConsulta trasladosEfc(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "nroTraslado", targetNamespace = "")
        String nroTraslado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DesgloseIngAutRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDesglosesIngAut", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDesglosesIngAut")
    @ResponseWrapper(localName = "consultarDesglosesIngAutResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDesglosesIngAutResponse")
    public DesgloseIngAutRespuestaConsulta consultarDesglosesIngAut(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param impExp
     * @param fechaIni
     * @param autenticacion
     * @param fechaFin
     * @return
     *     returns com.dna.deposito.DeclaracionListaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaDeclaracion", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracion")
    @ResponseWrapper(localName = "consultarListaDeclaracionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracionResponse")
    public DeclaracionListaRespuestaConsulta consultarListaDeclaracion(
        @WebParam(name = "fechaIni", targetNamespace = "")
        String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "impExp", targetNamespace = "")
        String impExp,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param filtroIntervencion
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.ConsultaIntervencionesResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaIntervencionesLineas", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultaIntervencionesLineas")
    @ResponseWrapper(localName = "consultaIntervencionesLineasResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultaIntervencionesLineasResponse")
    public ConsultaIntervencionesResp consultaIntervencionesLineas(
        @WebParam(name = "filtroIntervencion", targetNamespace = "")
        String filtroIntervencion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param despacho
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracionSinSalida", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSinSalida")
    @ResponseWrapper(localName = "consultarDeclaracionSinSalidaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSinSalidaResponse")
    public DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSinSalida(
        @WebParam(name = "despacho", targetNamespace = "")
        String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.ActaRecepcionRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actaRecepcion", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ActaRecepcion")
    @ResponseWrapper(localName = "actaRecepcionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ActaRecepcionResponse")
    public ActaRecepcionRespuestaConsulta actaRecepcion(
        @WebParam(name = "manifiesto", targetNamespace = "")
        String manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param bultosAIngresar
     * @param autenticacion
     * @param idManifiesto
     * @param indicadores
     * @param contenedorAIngresar
     * @param idTransaccionDeposito
     * @return
     *     returns com.dna.deposito.RespuestaTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDeposito")
    @ResponseWrapper(localName = "ingresoDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDepositoResponse")
    public RespuestaTransaccion ingresoDeposito(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        IdManifiesto idManifiesto,
        @WebParam(name = "indicadores", targetNamespace = "")
        Indicadores indicadores,
        @WebParam(name = "bultosAIngresar", targetNamespace = "")
        List<BultosAIngresar> bultosAIngresar,
        @WebParam(name = "contenedorAIngresar", targetNamespace = "")
        List<String> contenedorAIngresar,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param traslado
     * @return
     *     returns com.dna.deposito.TrasladoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoEfc", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoEfc")
    @ResponseWrapper(localName = "ingresoEfcResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoEfcResponse")
    public TrasladoRespuestaConsulta ingresoEfc(
        @WebParam(name = "traslado", targetNamespace = "")
        TaiViaje traslado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param expediente
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.ExpedienteThRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "expedienteTh", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ExpedienteTh")
    @ResponseWrapper(localName = "expedienteThResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ExpedienteThResponse")
    public ExpedienteThRespuestaConsulta expedienteTh(
        @WebParam(name = "expediente", targetNamespace = "")
        String expediente,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param idDeclaracionSimplificada
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracionSimplLiquidacion", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplLiquidacion")
    @ResponseWrapper(localName = "consultarDeclaracionSimplLiquidacionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplLiquidacionResponse")
    public DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplLiquidacion(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.ManifiestosTituloDepRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarManifiestosDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestosDeposito")
    @ResponseWrapper(localName = "consultarManifiestosDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestosDepositoResponse")
    public ManifiestosTituloDepRespuestaConsulta consultarManifiestosDeposito(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaIni
     * @param rucImportador
     * @param autenticacion
     * @param fechaFin
     * @return
     *     returns com.dna.deposito.DeclaracionListaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaDeclaracionLight", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracionLight")
    @ResponseWrapper(localName = "consultarListaDeclaracionLightResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracionLightResponse")
    public DeclaracionListaRespuestaConsulta consultarListaDeclaracionLight(
        @WebParam(name = "fechaIni", targetNamespace = "")
        String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "rucImportador", targetNamespace = "")
        String rucImportador,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.ManifiestosTituloRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "guiasSinOficializar", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.GuiasSinOficializar")
    @ResponseWrapper(localName = "guiasSinOficializarResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.GuiasSinOficializarResponse")
    public ManifiestosTituloRespuestaConsulta guiasSinOficializar(
        @WebParam(name = "manifiesto", targetNamespace = "")
        IdManifiesto manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param tipo
     * @param monto
     * @param autenticacion
     * @param documento
     * @return
     *     returns com.dna.deposito.BoletaCanonRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearBoletaCanon", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.CrearBoletaCanon")
    @ResponseWrapper(localName = "crearBoletaCanonResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.CrearBoletaCanonResponse")
    public BoletaCanonRespuesta crearBoletaCanon(
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "monto", targetNamespace = "")
        String monto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param documento
     * @return
     *     returns com.dna.deposito.TransporteInterRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTransporteInternacional", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarTransporteInternacional")
    @ResponseWrapper(localName = "consultarTransporteInternacionalResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarTransporteInternacionalResponse")
    public TransporteInterRespuestaConsulta consultarTransporteInternacional(
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param filtroInicio
     * @param filtroMatricula
     * @param filtroIntervencion
     * @param filtroPuerto
     * @param filtroAduana
     * @param autenticacion
     * @param filtroConocimiento
     * @param filtroPlaca
     * @param filtroFin
     * @return
     *     returns com.dna.deposito.ConsultaIntervencionesResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaIntervenciones", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultaIntervenciones")
    @ResponseWrapper(localName = "consultaIntervencionesResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultaIntervencionesResponse")
    public ConsultaIntervencionesResp consultaIntervenciones(
        @WebParam(name = "filtroInicio", targetNamespace = "")
        String filtroInicio,
        @WebParam(name = "filtroFin", targetNamespace = "")
        String filtroFin,
        @WebParam(name = "filtroPuerto", targetNamespace = "")
        String filtroPuerto,
        @WebParam(name = "filtroAduana", targetNamespace = "")
        String filtroAduana,
        @WebParam(name = "filtroMatricula", targetNamespace = "")
        String filtroMatricula,
        @WebParam(name = "filtroPlaca", targetNamespace = "")
        String filtroPlaca,
        @WebParam(name = "filtroIntervencion", targetNamespace = "")
        String filtroIntervencion,
        @WebParam(name = "filtroConocimiento", targetNamespace = "")
        String filtroConocimiento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param filtroIntervencion
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.ConsultaIntervencionesResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaIntervencionesContenedores", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultaIntervencionesContenedores")
    @ResponseWrapper(localName = "consultaIntervencionesContenedoresResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultaIntervencionesContenedoresResponse")
    public ConsultaIntervencionesResp consultaIntervencionesContenedores(
        @WebParam(name = "filtroIntervencion", targetNamespace = "")
        String filtroIntervencion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param rucExportador
     * @param fechaIngreso
     * @param notaRemision
     * @param autenticacion
     * @param declaracionnes
     * @param nroTimbrado
     * @return
     *     returns com.dna.deposito.IngRemiEfcRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoRemiEfcRegistrar", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoRemiEfcRegistrar")
    @ResponseWrapper(localName = "ingresoRemiEfcRegistrarResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoRemiEfcRegistrarResponse")
    public IngRemiEfcRespuesta ingresoRemiEfcRegistrar(
        @WebParam(name = "nroTimbrado", targetNamespace = "")
        String nroTimbrado,
        @WebParam(name = "notaRemision", targetNamespace = "")
        String notaRemision,
        @WebParam(name = "fechaIngreso", targetNamespace = "")
        String fechaIngreso,
        @WebParam(name = "rucExportador", targetNamespace = "")
        String rucExportador,
        @WebParam(name = "declaracionnes", targetNamespace = "")
        List<DeclaracionEfc> declaracionnes,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fecha
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.ManifiestoListaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaManifiesto", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaManifiesto")
    @ResponseWrapper(localName = "consultarListaManifiestoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaManifiestoResponse")
    public ManifiestoListaRespuestaConsulta consultarListaManifiesto(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param documento
     * @return
     *     returns com.dna.deposito.ImportadorRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarImportador", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarImportador")
    @ResponseWrapper(localName = "consultarImportadorResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarImportadorResponse")
    public ImportadorRespuestaConsulta consultarImportador(
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param idManifiesto
     * @return
     *     returns com.dna.deposito.ManifiestoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revertirDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.RevertirDeposito")
    @ResponseWrapper(localName = "revertirDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.RevertirDepositoResponse")
    public ManifiestoRespuestaConsulta revertirDeposito(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param idManifiesto
     * @return
     *     returns com.dna.deposito.ManifiestoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarManifiestoTema", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestoTema")
    @ResponseWrapper(localName = "consultarManifiestoTemaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestoTemaResponse")
    public ManifiestoRespuestaConsulta consultarManifiestoTema(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param afectaciones
     * @return
     *     returns com.dna.deposito.AfectacionesCanonRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afectacionesCanon", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.AfectacionesCanon")
    @ResponseWrapper(localName = "afectacionesCanonResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.AfectacionesCanonResponse")
    public AfectacionesCanonRespuesta afectacionesCanon(
        @WebParam(name = "afectaciones", targetNamespace = "")
        List<AfectarCanon> afectaciones,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fecha
     * @param autenticacion
     * @param moneda
     * @return
     *     returns com.dna.deposito.CotizacionRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCotizacion", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarCotizacion")
    @ResponseWrapper(localName = "consultarCotizacionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarCotizacionResponse")
    public CotizacionRespuestaConsulta consultarCotizacion(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "moneda", targetNamespace = "")
        String moneda,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param dBegin
     * @param burTarget
     * @param autenticacion
     * @param idso
     * @param mic
     * @param nroctd
     * @param dEnd
     * @param boleta
     * @param state
     * @param operType
     * @param burSource
     * @param trsp
     * @return
     *     returns com.dna.deposito.CodigoBarraRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCodigoBarra", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarCodigoBarra")
    @ResponseWrapper(localName = "consultarCodigoBarraResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarCodigoBarraResponse")
    public CodigoBarraRespuestaConsulta consultarCodigoBarra(
        @WebParam(name = "burSource", targetNamespace = "")
        String burSource,
        @WebParam(name = "burTarget", targetNamespace = "")
        String burTarget,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "nroctd", targetNamespace = "")
        String nroctd,
        @WebParam(name = "operType", targetNamespace = "")
        String operType,
        @WebParam(name = "idso", targetNamespace = "")
        String idso,
        @WebParam(name = "mic", targetNamespace = "")
        String mic,
        @WebParam(name = "boleta", targetNamespace = "")
        String boleta,
        @WebParam(name = "trsp", targetNamespace = "")
        String trsp,
        @WebParam(name = "dBegin", targetNamespace = "")
        String dBegin,
        @WebParam(name = "dEnd", targetNamespace = "")
        String dEnd,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param ruc
     * @param fechaIni
     * @param autenticacion
     * @param fechaFin
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaListaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaDecSimplPendGroup", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDecSimplPendGroup")
    @ResponseWrapper(localName = "consultarListaDecSimplPendGroupResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDecSimplPendGroupResponse")
    public DeclaracionSimplificadaListaRespuestaConsulta consultarListaDecSimplPendGroup(
        @WebParam(name = "fechaIni", targetNamespace = "")
        String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "ruc", targetNamespace = "")
        String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param nroTraslado
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.TrasladoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trasladoEfc", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.TrasladoEfc")
    @ResponseWrapper(localName = "trasladoEfcResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.TrasladoEfcResponse")
    public TrasladoRespuestaConsulta trasladoEfc(
        @WebParam(name = "nroTraslado", targetNamespace = "")
        String nroTraslado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @param titulo
     * @param prefijo
     * @return
     *     returns com.dna.deposito.GuiaMadreRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarGuiaMadre", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarGuiaMadre")
    @ResponseWrapper(localName = "consultarGuiaMadreResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarGuiaMadreResponse")
    public GuiaMadreRespuestaConsulta consultarGuiaMadre(
        @WebParam(name = "manifiesto", targetNamespace = "")
        String manifiesto,
        @WebParam(name = "prefijo", targetNamespace = "")
        String prefijo,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param cabeceraSalida
     * @param autenticacion
     * @param idTransaccionDeposito
     * @return
     *     returns com.dna.deposito.RespuestaSalida
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salidaZonaPrimaria", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.SalidaZonaPrimaria")
    @ResponseWrapper(localName = "salidaZonaPrimariaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.SalidaZonaPrimariaResponse")
    public RespuestaSalida salidaZonaPrimaria(
        @WebParam(name = "cabeceraSalida", targetNamespace = "")
        CabeceraSalida cabeceraSalida,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param cabeceraSalida
     * @param autenticacion
     * @param idTransaccionDeposito
     * @return
     *     returns com.dna.deposito.RespuestaSalida
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salidaZonaPrimariaRemate", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.SalidaZonaPrimariaRemate")
    @ResponseWrapper(localName = "salidaZonaPrimariaRemateResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.SalidaZonaPrimariaRemateResponse")
    public RespuestaSalida salidaZonaPrimariaRemate(
        @WebParam(name = "cabeceraSalida", targetNamespace = "")
        CabeceraSalida cabeceraSalida,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DesconsolidadoIngAutRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDesconsolidadosIngAut", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDesconsolidadosIngAut")
    @ResponseWrapper(localName = "consultarDesconsolidadosIngAutResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDesconsolidadosIngAutResponse")
    public DesconsolidadoIngAutRespuestaConsulta consultarDesconsolidadosIngAut(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param rucExportador
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.IngRemiReferenciaExportadorRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoRemiExportador", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoRemiExportador")
    @ResponseWrapper(localName = "ingresoRemiExportadorResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoRemiExportadorResponse")
    public IngRemiReferenciaExportadorRespuesta ingresoRemiExportador(
        @WebParam(name = "rucExportador", targetNamespace = "")
        String rucExportador,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param ruc
     * @param fechaIni
     * @param autenticacion
     * @param fechaFin
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaListaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaDecSimplLight", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDecSimplLight")
    @ResponseWrapper(localName = "consultarListaDecSimplLightResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDecSimplLightResponse")
    public DeclaracionSimplificadaListaRespuestaConsulta consultarListaDecSimplLight(
        @WebParam(name = "fechaIni", targetNamespace = "")
        String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "ruc", targetNamespace = "")
        String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param bultosAIngresar
     * @param autenticacion
     * @param idManifiesto
     * @param indicadores
     * @param contenedorAIngresar
     * @param idTransaccionDeposito
     * @return
     *     returns com.dna.deposito.RespuestaTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoNovedadesDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoNovedadesDeposito")
    @ResponseWrapper(localName = "ingresoNovedadesDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoNovedadesDepositoResponse")
    public RespuestaTransaccion ingresoNovedadesDeposito(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        IdManifiesto idManifiesto,
        @WebParam(name = "indicadores", targetNamespace = "")
        Indicadores indicadores,
        @WebParam(name = "bultosAIngresar", targetNamespace = "")
        List<BultosAIngresar> bultosAIngresar,
        @WebParam(name = "contenedorAIngresar", targetNamespace = "")
        List<String> contenedorAIngresar,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param ruc
     * @param tere
     * @param fechaIni
     * @param autenticacion
     * @param despacho
     * @param fechaFin
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaListaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaDeclaracionSimpl", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracionSimpl")
    @ResponseWrapper(localName = "consultarListaDeclaracionSimplResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaDeclaracionSimplResponse")
    public DeclaracionSimplificadaListaRespuestaConsulta consultarListaDeclaracionSimpl(
        @WebParam(name = "fechaIni", targetNamespace = "")
        String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin,
        @WebParam(name = "ruc", targetNamespace = "")
        String ruc,
        @WebParam(name = "tere", targetNamespace = "")
        String tere,
        @WebParam(name = "despacho", targetNamespace = "")
        String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param tere
     * @param manifiesto
     * @param autenticacion
     * @param titulo
     * @return
     *     returns com.dna.deposito.GuiasSinDespachoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarDespachoTere", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.VerificarDespachoTere")
    @ResponseWrapper(localName = "verificarDespachoTereResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.VerificarDespachoTereResponse")
    public GuiasSinDespachoResponse verificarDespachoTere(
        @WebParam(name = "tere", targetNamespace = "")
        String tere,
        @WebParam(name = "manifiesto", targetNamespace = "")
        String manifiesto,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.SolicitudIngAutRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSolicitudesIngAut", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarSolicitudesIngAut")
    @ResponseWrapper(localName = "consultarSolicitudesIngAutResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarSolicitudesIngAutResponse")
    public SolicitudIngAutRespuestaConsulta consultarSolicitudesIngAut(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param documento
     * @return
     *     returns com.dna.deposito.AgenteRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAgente", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarAgente")
    @ResponseWrapper(localName = "consultarAgenteResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarAgenteResponse")
    public AgenteRespuestaConsulta consultarAgente(
        @WebParam(name = "documento", targetNamespace = "")
        String documento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param idDeclaracionSimplificada
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DeclaracionSimplificadaRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracionSimplificadaAll", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplificadaAll")
    @ResponseWrapper(localName = "consultarDeclaracionSimplificadaAllResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionSimplificadaAllResponse")
    public DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplificadaAll(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param estado
     * @param autenticacion
     * @param identificador
     * @return
     *     returns com.dna.deposito.GuiasManifiestosPreviosRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarGuiasManifiestosPrevios", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarGuiasManifiestosPrevios")
    @ResponseWrapper(localName = "consultarGuiasManifiestosPreviosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarGuiasManifiestosPreviosResponse")
    public GuiasManifiestosPreviosRespuestaConsulta consultarGuiasManifiestosPrevios(
        @WebParam(name = "identificador", targetNamespace = "")
        String identificador,
        @WebParam(name = "estado", targetNamespace = "")
        String estado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param idManifiesto
     * @return
     *     returns com.dna.deposito.DesgloseRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDesglose", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDesglose")
    @ResponseWrapper(localName = "consultarDesgloseResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDesgloseResponse")
    public DesgloseRespuestaConsulta consultarDesglose(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param idManifiesto
     * @return
     *     returns com.dna.deposito.ManifiestoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarManifiesto", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiesto")
    @ResponseWrapper(localName = "consultarManifiestoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestoResponse")
    public ManifiestoRespuestaConsulta consultarManifiesto(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param despacho
     * @return
     *     returns com.dna.deposito.DeclaracionRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracionExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionExpo")
    @ResponseWrapper(localName = "consultarDeclaracionExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionExpoResponse")
    public DeclaracionRespuestaConsulta consultarDeclaracionExpo(
        @WebParam(name = "despacho", targetNamespace = "")
        String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param cabeceraListaSalida
     * @return
     *     returns com.dna.deposito.RespuestaListaSalida
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaSalidaZonaPrimaria", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ListaSalidaZonaPrimaria")
    @ResponseWrapper(localName = "listaSalidaZonaPrimariaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ListaSalidaZonaPrimariaResponse")
    public RespuestaListaSalida listaSalidaZonaPrimaria(
        @WebParam(name = "cabeceraListaSalida", targetNamespace = "")
        List<CabeceraSalida> cabeceraListaSalida,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @param titulo
     * @param prefijo
     * @return
     *     returns com.dna.deposito.BultosDeclaradosRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarBultosDeclarados", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarBultosDeclarados")
    @ResponseWrapper(localName = "consultarBultosDeclaradosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarBultosDeclaradosResponse")
    public BultosDeclaradosRespuestaConsulta consultarBultosDeclarados(
        @WebParam(name = "manifiesto", targetNamespace = "")
        String manifiesto,
        @WebParam(name = "prefijo", targetNamespace = "")
        String prefijo,
        @WebParam(name = "titulo", targetNamespace = "")
        String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param compania
     * @param fechaDesde
     * @param autenticacion
     * @param vuelo
     * @return
     *     returns com.dna.deposito.ManifiestosPreviosRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarManifiestosPrevios", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestosPrevios")
    @ResponseWrapper(localName = "consultarManifiestosPreviosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarManifiestosPreviosResponse")
    public ManifiestosPreviosRespuestaConsulta consultarManifiestosPrevios(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "vuelo", targetNamespace = "")
        String vuelo,
        @WebParam(name = "compania", targetNamespace = "")
        String compania,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param noRequiereIngreso
     * @param autenticacion
     * @param idDeclaracion
     * @return
     *     returns com.dna.deposito.DeclaracionRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracion", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracion")
    @ResponseWrapper(localName = "consultarDeclaracionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarDeclaracionResponse")
    public DeclaracionRespuestaConsulta consultarDeclaracion(
        @WebParam(name = "idDeclaracion", targetNamespace = "")
        String idDeclaracion,
        @WebParam(name = "noRequiereIngreso", targetNamespace = "")
        String noRequiereIngreso,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @param prefijoTitulo
     * @param numeroTitulo
     * @return
     *     returns com.dna.deposito.ManifiestosTituloRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaManifiestos", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaManifiestos")
    @ResponseWrapper(localName = "consultarListaManifiestosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.ConsultarListaManifiestosResponse")
    public ManifiestosTituloRespuestaConsulta consultarListaManifiestos(
        @WebParam(name = "numeroTitulo", targetNamespace = "")
        String numeroTitulo,
        @WebParam(name = "prefijoTitulo", targetNamespace = "")
        String prefijoTitulo,
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param declaracion
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.DespachoSimplTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salidaDespachoSimplExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.SalidaDespachoSimplExpo")
    @ResponseWrapper(localName = "salidaDespachoSimplExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.SalidaDespachoSimplExpoResponse")
    public DespachoSimplTransaccion salidaDespachoSimplExpo(
        @WebParam(name = "declaracion", targetNamespace = "")
        DeclaracionSimplificada declaracion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param rut
     * @param autenticacion
     * @return
     *     returns com.dna.deposito.TransitoRespuestaConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transito", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.Transito")
    @ResponseWrapper(localName = "transitoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.TransitoResponse")
    public TransitoRespuestaConsulta transito(
        @WebParam(name = "rut", targetNamespace = "")
        String rut,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param bultosAIngresar
     * @param autenticacion
     * @param idManifiesto
     * @param indicadores
     * @param contenedorAIngresar
     * @param idTransaccionDeposito
     * @return
     *     returns com.dna.deposito.RespuestaTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoDepositoTema", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDepositoTema")
    @ResponseWrapper(localName = "ingresoDepositoTemaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDepositoTemaResponse")
    public RespuestaTransaccion ingresoDepositoTema(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        IdManifiesto idManifiesto,
        @WebParam(name = "indicadores", targetNamespace = "")
        Indicadores indicadores,
        @WebParam(name = "bultosAIngresar", targetNamespace = "")
        List<BultosAIngresar> bultosAIngresar,
        @WebParam(name = "contenedorAIngresar", targetNamespace = "")
        List<String> contenedorAIngresar,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param nroTransito
     * @return
     *     returns com.dna.deposito.RespuestaTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoDepositoDocTrans", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDepositoDocTrans")
    @ResponseWrapper(localName = "ingresoDepositoDocTransResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "com.dna.deposito.IngresoDepositoDocTransResponse")
    public RespuestaTransaccion ingresoDepositoDocTrans(
        @WebParam(name = "nroTransito", targetNamespace = "")
        String nroTransito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

}
