package py.gov.aduana.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Sep 27 13:21:19 ART 2023
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://aduana.gov.py/webservices", name = "serviciodepositoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiciodepositoSoap {

    @WebMethod
    @RequestWrapper(localName = "verificarRetiroAnticipado", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.VerificarRetiroAnticipado")
    @ResponseWrapper(localName = "verificarRetiroAnticipadoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.VerificarRetiroAnticipadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ExpedienteThRespuestaConsulta verificarRetiroAnticipado(
        @WebParam(name = "despacho", targetNamespace = "")
        java.lang.String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarGuiasCou", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarGuiasCou")
    @ResponseWrapper(localName = "consultarGuiasCouResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarGuiasCouResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.CouRespuestaConsulta consultarGuiasCou(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "transitoCambioEstado", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.TransitoCambioEstado")
    @ResponseWrapper(localName = "transitoCambioEstadoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.TransitoCambioEstadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.TransitoRespuestaConsulta transitoCambioEstado(
        @WebParam(name = "sgtDta", targetNamespace = "")
        py.gov.aduana.webservices.SgtDta sgtDta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDespacho", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDespacho")
    @ResponseWrapper(localName = "consultarDespachoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDespachoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DespachoRespuestaConsulta consultarDespacho(
        @WebParam(name = "despacho", targetNamespace = "")
        java.lang.String despacho,
        @WebParam(name = "manifiesto", targetNamespace = "")
        java.lang.String manifiesto,
        @WebParam(name = "prefijo", targetNamespace = "")
        java.lang.String prefijo,
        @WebParam(name = "titulo", targetNamespace = "")
        java.lang.String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoRemiEfcConsultar", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoRemiEfcConsultar")
    @ResponseWrapper(localName = "ingresoRemiEfcConsultarResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoRemiEfcConsultarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.IngRemiEfcRespuesta ingresoRemiEfcConsultar(
        @WebParam(name = "nroDeclaracion", targetNamespace = "")
        java.lang.String nroDeclaracion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDeclaracionSimplificadaExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplificadaExpo")
    @ResponseWrapper(localName = "consultarDeclaracionSimplificadaExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplificadaExpoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplificadaExpo(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        java.lang.String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDeclaracionSimplificada", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplificada")
    @ResponseWrapper(localName = "consultarDeclaracionSimplificadaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplificadaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplificada(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        java.lang.String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarSaldoRuc", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarSaldoRuc")
    @ResponseWrapper(localName = "consultarSaldoRucResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarSaldoRucResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.SaldoRespuestaConsulta consultarSaldoRuc(
        @WebParam(name = "ruc", targetNamespace = "")
        java.lang.String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarTransitosSqf", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarTransitosSqf")
    @ResponseWrapper(localName = "consultarTransitosSqfResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarTransitosSqfResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.TransitoRespuestaConsultaSqf consultarTransitosSqf(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "rut", targetNamespace = "")
        java.lang.String rut,
        @WebParam(name = "abrevEstado", targetNamespace = "")
        java.lang.String abrevEstado,
        @WebParam(name = "aduanaOrigen", targetNamespace = "")
        java.lang.String aduanaOrigen,
        @WebParam(name = "aduanaDestino", targetNamespace = "")
        java.lang.String aduanaDestino,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaDeclaracionSimplGuia", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracionSimplGuia")
    @ResponseWrapper(localName = "consultarListaDeclaracionSimplGuiaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracionSimplGuiaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta consultarListaDeclaracionSimplGuia(
        @WebParam(name = "fechaIni", targetNamespace = "")
        java.lang.String fechaIni,
        @WebParam(name = "items", targetNamespace = "")
        java.util.List<py.gov.aduana.webservices.DeclaracionSimplificadaItem> items,
        @WebParam(name = "ruc", targetNamespace = "")
        java.lang.String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoDespachoSimplExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDespachoSimplExpo")
    @ResponseWrapper(localName = "ingresoDespachoSimplExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDespachoSimplExpoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DespachoSimplTransaccion ingresoDespachoSimplExpo(
        @WebParam(name = "declaracion", targetNamespace = "")
        py.gov.aduana.webservices.DeclaracionSimplificada declaracion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarManifiestoTitulo", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestoTitulo")
    @ResponseWrapper(localName = "consultarManifiestoTituloResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestoTituloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestoTituloRespuestaConsulta consultarManifiestoTitulo(
        @WebParam(name = "tipoMovimiento", targetNamespace = "")
        java.lang.String tipoMovimiento,
        @WebParam(name = "numeroTitulo", targetNamespace = "")
        java.lang.String numeroTitulo,
        @WebParam(name = "prefijoTitulo", targetNamespace = "")
        java.lang.String prefijoTitulo,
        @WebParam(name = "manifiesto", targetNamespace = "")
        java.lang.String manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "trasladosEfc", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.TrasladosEfc")
    @ResponseWrapper(localName = "trasladosEfcResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.TrasladosEfcResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.TrasladosRespuestaConsulta trasladosEfc(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "nroTraslado", targetNamespace = "")
        java.lang.String nroTraslado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDesglosesIngAut", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDesglosesIngAut")
    @ResponseWrapper(localName = "consultarDesglosesIngAutResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDesglosesIngAutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DesgloseIngAutRespuestaConsulta consultarDesglosesIngAut(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaDeclaracion", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracion")
    @ResponseWrapper(localName = "consultarListaDeclaracionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionListaRespuestaConsulta consultarListaDeclaracion(
        @WebParam(name = "fechaIni", targetNamespace = "")
        java.lang.String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        java.lang.String fechaFin,
        @WebParam(name = "impExp", targetNamespace = "")
        java.lang.String impExp,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultaIntervencionesLineas", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaIntervencionesLineas")
    @ResponseWrapper(localName = "consultaIntervencionesLineasResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaIntervencionesLineasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ConsultaIntervencionesResp consultaIntervencionesLineas(
        @WebParam(name = "filtroIntervencion", targetNamespace = "")
        java.lang.String filtroIntervencion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDeclaracionSinSalida", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSinSalida")
    @ResponseWrapper(localName = "consultarDeclaracionSinSalidaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSinSalidaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSinSalida(
        @WebParam(name = "despacho", targetNamespace = "")
        java.lang.String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "actaRecepcion", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ActaRecepcion")
    @ResponseWrapper(localName = "actaRecepcionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ActaRecepcionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ActaRecepcionRespuestaConsulta actaRecepcion(
        @WebParam(name = "manifiesto", targetNamespace = "")
        java.lang.String manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDeposito")
    @ResponseWrapper(localName = "ingresoDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.RespuestaTransaccion ingresoDeposito(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto idManifiesto,
        @WebParam(name = "indicadores", targetNamespace = "")
        py.gov.aduana.webservices.Indicadores indicadores,
        @WebParam(name = "bultosAIngresar", targetNamespace = "")
        java.util.List<py.gov.aduana.webservices.BultosAIngresar> bultosAIngresar,
        @WebParam(name = "contenedorAIngresar", targetNamespace = "")
        java.util.List<java.lang.String> contenedorAIngresar,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        java.lang.String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoEfc", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoEfc")
    @ResponseWrapper(localName = "ingresoEfcResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoEfcResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.TrasladoRespuestaConsulta ingresoEfc(
        @WebParam(name = "traslado", targetNamespace = "")
        py.gov.aduana.webservices.TaiViaje traslado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "expedienteTh", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ExpedienteTh")
    @ResponseWrapper(localName = "expedienteThResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ExpedienteThResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ExpedienteThRespuestaConsulta expedienteTh(
        @WebParam(name = "expediente", targetNamespace = "")
        java.lang.String expediente,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDeclaracionSimplLiquidacion", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplLiquidacion")
    @ResponseWrapper(localName = "consultarDeclaracionSimplLiquidacionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplLiquidacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplLiquidacion(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        java.lang.String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarManifiestosDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestosDeposito")
    @ResponseWrapper(localName = "consultarManifiestosDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestosDepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestosTituloDepRespuestaConsulta consultarManifiestosDeposito(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaDeclaracionLight", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracionLight")
    @ResponseWrapper(localName = "consultarListaDeclaracionLightResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracionLightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionListaRespuestaConsulta consultarListaDeclaracionLight(
        @WebParam(name = "fechaIni", targetNamespace = "")
        java.lang.String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        java.lang.String fechaFin,
        @WebParam(name = "rucImportador", targetNamespace = "")
        java.lang.String rucImportador,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "guiasSinOficializar", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.GuiasSinOficializar")
    @ResponseWrapper(localName = "guiasSinOficializarResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.GuiasSinOficializarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestosTituloRespuestaConsulta guiasSinOficializar(
        @WebParam(name = "manifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "crearBoletaCanon", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.CrearBoletaCanon")
    @ResponseWrapper(localName = "crearBoletaCanonResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.CrearBoletaCanonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.BoletaCanonRespuesta crearBoletaCanon(
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.String tipo,
        @WebParam(name = "monto", targetNamespace = "")
        java.lang.String monto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarTransporteInternacional", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarTransporteInternacional")
    @ResponseWrapper(localName = "consultarTransporteInternacionalResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarTransporteInternacionalResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.TransporteInterRespuestaConsulta consultarTransporteInternacional(
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultaIntervenciones", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaIntervenciones")
    @ResponseWrapper(localName = "consultaIntervencionesResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaIntervencionesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ConsultaIntervencionesResp consultaIntervenciones(
        @WebParam(name = "filtroInicio", targetNamespace = "")
        java.lang.String filtroInicio,
        @WebParam(name = "filtroFin", targetNamespace = "")
        java.lang.String filtroFin,
        @WebParam(name = "filtroPuerto", targetNamespace = "")
        java.lang.String filtroPuerto,
        @WebParam(name = "filtroAduana", targetNamespace = "")
        java.lang.String filtroAduana,
        @WebParam(name = "filtroMatricula", targetNamespace = "")
        java.lang.String filtroMatricula,
        @WebParam(name = "filtroPlaca", targetNamespace = "")
        java.lang.String filtroPlaca,
        @WebParam(name = "filtroIntervencion", targetNamespace = "")
        java.lang.String filtroIntervencion,
        @WebParam(name = "filtroConocimiento", targetNamespace = "")
        java.lang.String filtroConocimiento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultaIntervencionesContenedores", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaIntervencionesContenedores")
    @ResponseWrapper(localName = "consultaIntervencionesContenedoresResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaIntervencionesContenedoresResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ConsultaIntervencionesResp consultaIntervencionesContenedores(
        @WebParam(name = "filtroIntervencion", targetNamespace = "")
        java.lang.String filtroIntervencion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoRemiEfcRegistrar", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoRemiEfcRegistrar")
    @ResponseWrapper(localName = "ingresoRemiEfcRegistrarResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoRemiEfcRegistrarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.IngRemiEfcRespuesta ingresoRemiEfcRegistrar(
        @WebParam(name = "nroTimbrado", targetNamespace = "")
        java.lang.String nroTimbrado,
        @WebParam(name = "notaRemision", targetNamespace = "")
        java.lang.String notaRemision,
        @WebParam(name = "fechaIngreso", targetNamespace = "")
        java.lang.String fechaIngreso,
        @WebParam(name = "rucExportador", targetNamespace = "")
        java.lang.String rucExportador,
        @WebParam(name = "declaracionnes", targetNamespace = "")
        java.util.List<py.gov.aduana.webservices.DeclaracionEfc> declaracionnes,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaManifiesto", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaManifiesto")
    @ResponseWrapper(localName = "consultarListaManifiestoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaManifiestoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestoListaRespuestaConsulta consultarListaManifiesto(
        @WebParam(name = "fecha", targetNamespace = "")
        java.lang.String fecha,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarImportador", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarImportador")
    @ResponseWrapper(localName = "consultarImportadorResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarImportadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ImportadorRespuestaConsulta consultarImportador(
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "revertirDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.RevertirDeposito")
    @ResponseWrapper(localName = "revertirDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.RevertirDepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestoRespuestaConsulta revertirDeposito(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarManifiestoTema", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestoTema")
    @ResponseWrapper(localName = "consultarManifiestoTemaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestoTemaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestoRespuestaConsulta consultarManifiestoTema(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "afectacionesCanon", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AfectacionesCanon")
    @ResponseWrapper(localName = "afectacionesCanonResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AfectacionesCanonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.AfectacionesCanonRespuesta afectacionesCanon(
        @WebParam(name = "afectaciones", targetNamespace = "")
        java.util.List<py.gov.aduana.webservices.AfectarCanon> afectaciones,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarCotizacion", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarCotizacion")
    @ResponseWrapper(localName = "consultarCotizacionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarCotizacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.CotizacionRespuestaConsulta consultarCotizacion(
        @WebParam(name = "fecha", targetNamespace = "")
        java.lang.String fecha,
        @WebParam(name = "moneda", targetNamespace = "")
        java.lang.String moneda,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarCodigoBarra", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarCodigoBarra")
    @ResponseWrapper(localName = "consultarCodigoBarraResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarCodigoBarraResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.CodigoBarraRespuestaConsulta consultarCodigoBarra(
        @WebParam(name = "burSource", targetNamespace = "")
        java.lang.String burSource,
        @WebParam(name = "burTarget", targetNamespace = "")
        java.lang.String burTarget,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state,
        @WebParam(name = "nroctd", targetNamespace = "")
        java.lang.String nroctd,
        @WebParam(name = "operType", targetNamespace = "")
        java.lang.String operType,
        @WebParam(name = "idso", targetNamespace = "")
        java.lang.String idso,
        @WebParam(name = "mic", targetNamespace = "")
        java.lang.String mic,
        @WebParam(name = "boleta", targetNamespace = "")
        java.lang.String boleta,
        @WebParam(name = "trsp", targetNamespace = "")
        java.lang.String trsp,
        @WebParam(name = "dBegin", targetNamespace = "")
        java.lang.String dBegin,
        @WebParam(name = "dEnd", targetNamespace = "")
        java.lang.String dEnd,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaDecSimplPendGroup", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDecSimplPendGroup")
    @ResponseWrapper(localName = "consultarListaDecSimplPendGroupResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDecSimplPendGroupResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta consultarListaDecSimplPendGroup(
        @WebParam(name = "fechaIni", targetNamespace = "")
        java.lang.String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        java.lang.String fechaFin,
        @WebParam(name = "ruc", targetNamespace = "")
        java.lang.String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "trasladoEfc", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.TrasladoEfc")
    @ResponseWrapper(localName = "trasladoEfcResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.TrasladoEfcResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.TrasladoRespuestaConsulta trasladoEfc(
        @WebParam(name = "nroTraslado", targetNamespace = "")
        java.lang.String nroTraslado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarGuiaMadre", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarGuiaMadre")
    @ResponseWrapper(localName = "consultarGuiaMadreResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarGuiaMadreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.GuiaMadreRespuestaConsulta consultarGuiaMadre(
        @WebParam(name = "manifiesto", targetNamespace = "")
        java.lang.String manifiesto,
        @WebParam(name = "prefijo", targetNamespace = "")
        java.lang.String prefijo,
        @WebParam(name = "titulo", targetNamespace = "")
        java.lang.String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "salidaZonaPrimaria", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.SalidaZonaPrimaria")
    @ResponseWrapper(localName = "salidaZonaPrimariaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.SalidaZonaPrimariaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.RespuestaSalida salidaZonaPrimaria(
        @WebParam(name = "cabeceraSalida", targetNamespace = "")
        py.gov.aduana.webservices.CabeceraSalida cabeceraSalida,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        java.lang.String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "salidaZonaPrimariaRemate", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.SalidaZonaPrimariaRemate")
    @ResponseWrapper(localName = "salidaZonaPrimariaRemateResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.SalidaZonaPrimariaRemateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.RespuestaSalida salidaZonaPrimariaRemate(
        @WebParam(name = "cabeceraSalida", targetNamespace = "")
        py.gov.aduana.webservices.CabeceraSalida cabeceraSalida,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        java.lang.String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDesconsolidadosIngAut", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDesconsolidadosIngAut")
    @ResponseWrapper(localName = "consultarDesconsolidadosIngAutResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDesconsolidadosIngAutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DesconsolidadoIngAutRespuestaConsulta consultarDesconsolidadosIngAut(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoRemiExportador", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoRemiExportador")
    @ResponseWrapper(localName = "ingresoRemiExportadorResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoRemiExportadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.IngRemiReferenciaExportadorRespuesta ingresoRemiExportador(
        @WebParam(name = "rucExportador", targetNamespace = "")
        java.lang.String rucExportador,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaDecSimplLight", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDecSimplLight")
    @ResponseWrapper(localName = "consultarListaDecSimplLightResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDecSimplLightResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta consultarListaDecSimplLight(
        @WebParam(name = "fechaIni", targetNamespace = "")
        java.lang.String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        java.lang.String fechaFin,
        @WebParam(name = "ruc", targetNamespace = "")
        java.lang.String ruc,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoNovedadesDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoNovedadesDeposito")
    @ResponseWrapper(localName = "ingresoNovedadesDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoNovedadesDepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.RespuestaTransaccion ingresoNovedadesDeposito(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto idManifiesto,
        @WebParam(name = "indicadores", targetNamespace = "")
        py.gov.aduana.webservices.Indicadores indicadores,
        @WebParam(name = "bultosAIngresar", targetNamespace = "")
        java.util.List<py.gov.aduana.webservices.BultosAIngresar> bultosAIngresar,
        @WebParam(name = "contenedorAIngresar", targetNamespace = "")
        java.util.List<java.lang.String> contenedorAIngresar,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        java.lang.String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaDeclaracionSimpl", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracionSimpl")
    @ResponseWrapper(localName = "consultarListaDeclaracionSimplResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaDeclaracionSimplResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta consultarListaDeclaracionSimpl(
        @WebParam(name = "fechaIni", targetNamespace = "")
        java.lang.String fechaIni,
        @WebParam(name = "fechaFin", targetNamespace = "")
        java.lang.String fechaFin,
        @WebParam(name = "ruc", targetNamespace = "")
        java.lang.String ruc,
        @WebParam(name = "tere", targetNamespace = "")
        java.lang.String tere,
        @WebParam(name = "despacho", targetNamespace = "")
        java.lang.String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "verificarDespachoTere", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.VerificarDespachoTere")
    @ResponseWrapper(localName = "verificarDespachoTereResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.VerificarDespachoTereResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.GuiasSinDespachoResponse verificarDespachoTere(
        @WebParam(name = "tere", targetNamespace = "")
        java.lang.String tere,
        @WebParam(name = "manifiesto", targetNamespace = "")
        java.lang.String manifiesto,
        @WebParam(name = "titulo", targetNamespace = "")
        java.lang.String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarSolicitudesIngAut", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarSolicitudesIngAut")
    @ResponseWrapper(localName = "consultarSolicitudesIngAutResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarSolicitudesIngAutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.SolicitudIngAutRespuestaConsulta consultarSolicitudesIngAut(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarAgente", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarAgente")
    @ResponseWrapper(localName = "consultarAgenteResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarAgenteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.AgenteRespuestaConsulta consultarAgente(
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDeclaracionSimplificadaAll", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplificadaAll")
    @ResponseWrapper(localName = "consultarDeclaracionSimplificadaAllResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionSimplificadaAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta consultarDeclaracionSimplificadaAll(
        @WebParam(name = "idDeclaracionSimplificada", targetNamespace = "")
        java.lang.String idDeclaracionSimplificada,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarGuiasManifiestosPrevios", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarGuiasManifiestosPrevios")
    @ResponseWrapper(localName = "consultarGuiasManifiestosPreviosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarGuiasManifiestosPreviosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.GuiasManifiestosPreviosRespuestaConsulta consultarGuiasManifiestosPrevios(
        @WebParam(name = "identificador", targetNamespace = "")
        java.lang.String identificador,
        @WebParam(name = "estado", targetNamespace = "")
        java.lang.String estado,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDesglose", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDesglose")
    @ResponseWrapper(localName = "consultarDesgloseResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDesgloseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DesgloseRespuestaConsulta consultarDesglose(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarManifiesto", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiesto")
    @ResponseWrapper(localName = "consultarManifiestoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestoRespuestaConsulta consultarManifiesto(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto idManifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDeclaracionExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionExpo")
    @ResponseWrapper(localName = "consultarDeclaracionExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionExpoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionRespuestaConsulta consultarDeclaracionExpo(
        @WebParam(name = "despacho", targetNamespace = "")
        java.lang.String despacho,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "listaSalidaZonaPrimaria", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ListaSalidaZonaPrimaria")
    @ResponseWrapper(localName = "listaSalidaZonaPrimariaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ListaSalidaZonaPrimariaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.RespuestaListaSalida listaSalidaZonaPrimaria(
        @WebParam(name = "cabeceraListaSalida", targetNamespace = "")
        java.util.List<py.gov.aduana.webservices.CabeceraSalida> cabeceraListaSalida,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarBultosDeclarados", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarBultosDeclarados")
    @ResponseWrapper(localName = "consultarBultosDeclaradosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarBultosDeclaradosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.BultosDeclaradosRespuestaConsulta consultarBultosDeclarados(
        @WebParam(name = "manifiesto", targetNamespace = "")
        java.lang.String manifiesto,
        @WebParam(name = "prefijo", targetNamespace = "")
        java.lang.String prefijo,
        @WebParam(name = "titulo", targetNamespace = "")
        java.lang.String titulo,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarManifiestosPrevios", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestosPrevios")
    @ResponseWrapper(localName = "consultarManifiestosPreviosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarManifiestosPreviosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestosPreviosRespuestaConsulta consultarManifiestosPrevios(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "vuelo", targetNamespace = "")
        java.lang.String vuelo,
        @WebParam(name = "compania", targetNamespace = "")
        java.lang.String compania,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarDeclaracion", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracion")
    @ResponseWrapper(localName = "consultarDeclaracionResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarDeclaracionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DeclaracionRespuestaConsulta consultarDeclaracion(
        @WebParam(name = "idDeclaracion", targetNamespace = "")
        java.lang.String idDeclaracion,
        @WebParam(name = "noRequiereIngreso", targetNamespace = "")
        java.lang.String noRequiereIngreso,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "consultarListaManifiestos", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaManifiestos")
    @ResponseWrapper(localName = "consultarListaManifiestosResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaManifiestosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.ManifiestosTituloRespuestaConsulta consultarListaManifiestos(
        @WebParam(name = "numeroTitulo", targetNamespace = "")
        java.lang.String numeroTitulo,
        @WebParam(name = "prefijoTitulo", targetNamespace = "")
        java.lang.String prefijoTitulo,
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "salidaDespachoSimplExpo", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.SalidaDespachoSimplExpo")
    @ResponseWrapper(localName = "salidaDespachoSimplExpoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.SalidaDespachoSimplExpoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.DespachoSimplTransaccion salidaDespachoSimplExpo(
        @WebParam(name = "declaracion", targetNamespace = "")
        py.gov.aduana.webservices.DeclaracionSimplificada declaracion,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "transito", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.Transito")
    @ResponseWrapper(localName = "transitoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.TransitoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.TransitoRespuestaConsulta transito(
        @WebParam(name = "rut", targetNamespace = "")
        java.lang.String rut,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoDepositoTema", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDepositoTema")
    @ResponseWrapper(localName = "ingresoDepositoTemaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDepositoTemaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.RespuestaTransaccion ingresoDepositoTema(
        @WebParam(name = "idManifiesto", targetNamespace = "")
        py.gov.aduana.webservices.IdManifiesto idManifiesto,
        @WebParam(name = "indicadores", targetNamespace = "")
        py.gov.aduana.webservices.Indicadores indicadores,
        @WebParam(name = "bultosAIngresar", targetNamespace = "")
        java.util.List<py.gov.aduana.webservices.BultosAIngresar> bultosAIngresar,
        @WebParam(name = "contenedorAIngresar", targetNamespace = "")
        java.util.List<java.lang.String> contenedorAIngresar,
        @WebParam(name = "idTransaccionDeposito", targetNamespace = "")
        java.lang.String idTransaccionDeposito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );

    @WebMethod
    @RequestWrapper(localName = "ingresoDepositoDocTrans", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDepositoDocTrans")
    @ResponseWrapper(localName = "ingresoDepositoDocTransResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDepositoDocTransResponse")
    @WebResult(name = "return", targetNamespace = "")
    public py.gov.aduana.webservices.RespuestaTransaccion ingresoDepositoDocTrans(
        @WebParam(name = "nroTransito", targetNamespace = "")
        java.lang.String nroTransito,
        @WebParam(name = "autenticacion", targetNamespace = "")
        py.gov.aduana.webservices.Autenticacion autenticacion
    );
}
