
/*
 * 
 */

package py.gov.aduana.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Sep 27 13:21:19 ART 2023
 * Generated source version: 2.2.5
 * 
 */


@WebServiceClient(name = "serviciodeposito", 
                  wsdlLocation = "https://securetest.aduana.gov.py/sgd2/serviciodeposito?wsdl",
                  targetNamespace = "http://aduana.gov.py/webservices") 
public class Serviciodeposito extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://aduana.gov.py/webservices", "serviciodeposito");
    public final static QName ServiciodepositoSoap = new QName("http://aduana.gov.py/webservices", "serviciodepositoSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://securetest.aduana.gov.py/sgd2/serviciodeposito?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://securetest.aduana.gov.py/sgd2/serviciodeposito?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Serviciodeposito(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Serviciodeposito(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Serviciodeposito() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ServiciodepositoSoap
     */
    @WebEndpoint(name = "serviciodepositoSoap")
    public ServiciodepositoSoap getServiciodepositoSoap() {
        return super.getPort(ServiciodepositoSoap, ServiciodepositoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciodepositoSoap
     */
    @WebEndpoint(name = "serviciodepositoSoap")
    public ServiciodepositoSoap getServiciodepositoSoap(WebServiceFeature... features) {
        return super.getPort(ServiciodepositoSoap, ServiciodepositoSoap.class, features);
    }

}
