
package py.gov.aduana.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import java.io.IOException;
import java.util.Map;
import javax.security.auth.callback.Callback;
import javax.security.auth.callback.CallbackHandler;
import javax.security.auth.callback.UnsupportedCallbackException;
import javax.xml.ws.BindingProvider;
import org.apache.cxf.ws.security.SecurityConstants;
//import org.apache.wss4j.common.ext.WSPasswordCallback;
import org.apache.ws.security.WSPasswordCallback;
/**
 * This class was generated by Apache CXF 2.2.5 Wed Sep 27 10:43:54 ART 2023
 * Generated source version: 2.2.5
 * 
 */

public final class ServiciodepositoSoap_ServiciodepositoSoap_Client {

	private static final QName SERVICE_NAME = new QName("http://aduana.gov.py/webservices", "serviciodeposito");

	private ServiciodepositoSoap_ServiciodepositoSoap_Client() {
	}

	public static void main(String args[]) throws Exception {
		URL wsdlURL = Serviciodeposito.WSDL_LOCATION;
		if (args.length > 0) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		Serviciodeposito ss = new Serviciodeposito(wsdlURL, SERVICE_NAME);
		ServiciodepositoSoap port = ss.getServiciodepositoSoap();
		Map<String, Object> properties = ((BindingProvider) port).getRequestContext();
		properties.put(SecurityConstants.SIGNATURE_USERNAME, "800637321");
		properties.put(SecurityConstants.CALLBACK_HANDLER, new CallbackHandler() {
			@Override
			public void handle(Callback[] callbacks) throws IOException, UnsupportedCallbackException {
				for (Callback cb : callbacks) {
					WSPasswordCallback pcb = (WSPasswordCallback) cb;
					if (pcb.getIdentifier().equals("800637321")) {
						pcb.setPassword("Ptp2023");
					}
				}
			}
		});
		ServiciodepositoSoap_ServiciodepositoSoap_Client res = new ServiciodepositoSoap_ServiciodepositoSoap_Client();
		java.net.URL url = res.getClass().getResource("/800637321.properties");
		properties.put(SecurityConstants.SIGNATURE_PROPERTIES, res.getClass().getResource("/800637321.properties"));
		properties.put(SecurityConstants.ENCRYPT_PROPERTIES, res.getClass().getResource("/800637321.properties"));
		properties.put(SecurityConstants.ENCRYPT_USERNAME, "sipsws");
		properties.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "https://securetest.aduana.gov.py/sgd2/serviciodeposito");
		
		Autenticacion auth = new Autenticacion();
		auth.setToken("CjxhdXRoPgoJPGlkIHVuaXF1ZV9pZD0iMSIgc3JjPSJDPXB5LCBPPWRuYSwgT1U9c29maWEsIENOPXdzYWF0ZXN0IiBnZW5fdGltZT0iMjAyMy0wOS0yN1QxMTo0OTo1OC4wMDAtMDM6MDAiIGV4cF90aW1lPSIyMDIzLTA5LTI4VDExOjQ5OjU4LjAwMC0wMzowMCIvPgoJPG9wZXJhdGlvbiB2YWx1ZT0iZ3JhbnRlZCIgdHlwZT0ibG9naW4iPgoJCTxsb2dpbiB1aWQ9IkM9UFksIE89UFRQLCBPVT1USSwgQ049ODAwNjM3MzIxIiBzZXJ2aWNlPSJzZXJ2aWNpb3NpcCIgYXV0aG1ldGhvZD0iY21zIj4KCQk8L2xvZ2luPgoJPC9vcGVyYXRpb24");
		auth.setFirma("FbZjP7ItpNGktZP/WpiWMRPzi2JqAKi/TCC+HPOKEoL9ejwO/SDZ8AeIBCb553WEOLNHT/Xn7b3g+bRcPNVmmsxqm1r8b31UrXwHhHiuxPd2tA00Sj6BlJgFUzbqQ/ZsxshI/Yu74YZjfUU5c/l+LUoW/qpYWNTIh9SJRE38g1xgt90liZ5kdMiT+xBl4tPgV8rS4VGfT7G9eNcBjnqxLllbcafKpZxzV19xXQzigRjBQv7qv5WM5FP+5w/K1Civ1iZG2gTCMQG/yROXmYw4ivcy9T67hUgwo/XGyuKn7P6ZsBF+Y7It9Bf67GlkF8aMzozaStCFpui8SD8k3WSj8g==");
		auth.setCodAduana("704");
		auth.setUsuario("800637321");

		{
			System.out.println("Invoking consultarImportador...");
			java.lang.String _consultarImportador_documento = "9876543210";
			py.gov.aduana.webservices.Autenticacion _consultarImportador_autenticacion = auth;
			py.gov.aduana.webservices.ImportadorRespuestaConsulta _consultarImportador__return = port
					.consultarImportador(_consultarImportador_documento, _consultarImportador_autenticacion);
			System.out.println("consultarImportador.result=" + _consultarImportador__return);

		}

		/*
		 * { System.out.println("Invoking verificarRetiroAnticipado...");
		 * java.lang.String _verificarRetiroAnticipado_despacho = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _verificarRetiroAnticipado_autenticacion = null;
		 * py.gov.aduana.webservices.ExpedienteThRespuestaConsulta
		 * _verificarRetiroAnticipado__return =
		 * port.verificarRetiroAnticipado(_verificarRetiroAnticipado_despacho,
		 * _verificarRetiroAnticipado_autenticacion);
		 * System.out.println("verificarRetiroAnticipado.result=" +
		 * _verificarRetiroAnticipado__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarGuiasCou..."); java.lang.String
		 * _consultarGuiasCou_fechaDesde = ""; java.lang.String
		 * _consultarGuiasCou_fechaHasta = ""; py.gov.aduana.webservices.Autenticacion
		 * _consultarGuiasCou_autenticacion = null;
		 * py.gov.aduana.webservices.CouRespuestaConsulta _consultarGuiasCou__return =
		 * port.consultarGuiasCou(_consultarGuiasCou_fechaDesde,
		 * _consultarGuiasCou_fechaHasta, _consultarGuiasCou_autenticacion);
		 * System.out.println("consultarGuiasCou.result=" + _consultarGuiasCou__return);
		 * 
		 * 
		 * } { System.out.println("Invoking transitoCambioEstado...");
		 * py.gov.aduana.webservices.SgtDta _transitoCambioEstado_sgtDta = null;
		 * py.gov.aduana.webservices.Autenticacion _transitoCambioEstado_autenticacion =
		 * null; py.gov.aduana.webservices.TransitoRespuestaConsulta
		 * _transitoCambioEstado__return =
		 * port.transitoCambioEstado(_transitoCambioEstado_sgtDta,
		 * _transitoCambioEstado_autenticacion);
		 * System.out.println("transitoCambioEstado.result=" +
		 * _transitoCambioEstado__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDespacho..."); java.lang.String
		 * _consultarDespacho_despacho = ""; java.lang.String
		 * _consultarDespacho_manifiesto = ""; java.lang.String
		 * _consultarDespacho_prefijo = ""; java.lang.String _consultarDespacho_titulo =
		 * ""; py.gov.aduana.webservices.Autenticacion _consultarDespacho_autenticacion
		 * = null; py.gov.aduana.webservices.DespachoRespuestaConsulta
		 * _consultarDespacho__return =
		 * port.consultarDespacho(_consultarDespacho_despacho,
		 * _consultarDespacho_manifiesto, _consultarDespacho_prefijo,
		 * _consultarDespacho_titulo, _consultarDespacho_autenticacion);
		 * System.out.println("consultarDespacho.result=" + _consultarDespacho__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoRemiEfcConsultar...");
		 * java.lang.String _ingresoRemiEfcConsultar_nroDeclaracion = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _ingresoRemiEfcConsultar_autenticacion = null;
		 * py.gov.aduana.webservices.IngRemiEfcRespuesta
		 * _ingresoRemiEfcConsultar__return =
		 * port.ingresoRemiEfcConsultar(_ingresoRemiEfcConsultar_nroDeclaracion,
		 * _ingresoRemiEfcConsultar_autenticacion);
		 * System.out.println("ingresoRemiEfcConsultar.result=" +
		 * _ingresoRemiEfcConsultar__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDeclaracionSimplificadaExpo...");
		 * java.lang.String
		 * _consultarDeclaracionSimplificadaExpo_idDeclaracionSimplificada = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarDeclaracionSimplificadaExpo_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta
		 * _consultarDeclaracionSimplificadaExpo__return =
		 * port.consultarDeclaracionSimplificadaExpo(
		 * _consultarDeclaracionSimplificadaExpo_idDeclaracionSimplificada,
		 * _consultarDeclaracionSimplificadaExpo_autenticacion);
		 * System.out.println("consultarDeclaracionSimplificadaExpo.result=" +
		 * _consultarDeclaracionSimplificadaExpo__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDeclaracionSimplificada...");
		 * java.lang.String _consultarDeclaracionSimplificada_idDeclaracionSimplificada
		 * = ""; py.gov.aduana.webservices.Autenticacion
		 * _consultarDeclaracionSimplificada_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta
		 * _consultarDeclaracionSimplificada__return =
		 * port.consultarDeclaracionSimplificada(
		 * _consultarDeclaracionSimplificada_idDeclaracionSimplificada,
		 * _consultarDeclaracionSimplificada_autenticacion);
		 * System.out.println("consultarDeclaracionSimplificada.result=" +
		 * _consultarDeclaracionSimplificada__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarSaldoRuc..."); java.lang.String
		 * _consultarSaldoRuc_ruc = ""; py.gov.aduana.webservices.Autenticacion
		 * _consultarSaldoRuc_autenticacion = null;
		 * py.gov.aduana.webservices.SaldoRespuestaConsulta _consultarSaldoRuc__return =
		 * port.consultarSaldoRuc(_consultarSaldoRuc_ruc,
		 * _consultarSaldoRuc_autenticacion);
		 * System.out.println("consultarSaldoRuc.result=" + _consultarSaldoRuc__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarTransitosSqf..."); java.lang.String
		 * _consultarTransitosSqf_fechaDesde = ""; java.lang.String
		 * _consultarTransitosSqf_fechaHasta = ""; java.lang.String
		 * _consultarTransitosSqf_rut = ""; java.lang.String
		 * _consultarTransitosSqf_abrevEstado = ""; java.lang.String
		 * _consultarTransitosSqf_aduanaOrigen = ""; java.lang.String
		 * _consultarTransitosSqf_aduanaDestino = "";
		 * py.gov.aduana.webservices.Autenticacion _consultarTransitosSqf_autenticacion
		 * = null; py.gov.aduana.webservices.TransitoRespuestaConsultaSqf
		 * _consultarTransitosSqf__return =
		 * port.consultarTransitosSqf(_consultarTransitosSqf_fechaDesde,
		 * _consultarTransitosSqf_fechaHasta, _consultarTransitosSqf_rut,
		 * _consultarTransitosSqf_abrevEstado, _consultarTransitosSqf_aduanaOrigen,
		 * _consultarTransitosSqf_aduanaDestino, _consultarTransitosSqf_autenticacion);
		 * System.out.println("consultarTransitosSqf.result=" +
		 * _consultarTransitosSqf__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaDeclaracionSimplGuia...");
		 * java.lang.String _consultarListaDeclaracionSimplGuia_fechaIni = "";
		 * java.util.List<py.gov.aduana.webservices.DeclaracionSimplificadaItem>
		 * _consultarListaDeclaracionSimplGuia_items = null; java.lang.String
		 * _consultarListaDeclaracionSimplGuia_ruc = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaDeclaracionSimplGuia_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta
		 * _consultarListaDeclaracionSimplGuia__return =
		 * port.consultarListaDeclaracionSimplGuia(
		 * _consultarListaDeclaracionSimplGuia_fechaIni,
		 * _consultarListaDeclaracionSimplGuia_items,
		 * _consultarListaDeclaracionSimplGuia_ruc,
		 * _consultarListaDeclaracionSimplGuia_autenticacion);
		 * System.out.println("consultarListaDeclaracionSimplGuia.result=" +
		 * _consultarListaDeclaracionSimplGuia__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoDespachoSimplExpo...");
		 * py.gov.aduana.webservices.DeclaracionSimplificada
		 * _ingresoDespachoSimplExpo_declaracion = null;
		 * py.gov.aduana.webservices.Autenticacion
		 * _ingresoDespachoSimplExpo_autenticacion = null;
		 * py.gov.aduana.webservices.DespachoSimplTransaccion
		 * _ingresoDespachoSimplExpo__return =
		 * port.ingresoDespachoSimplExpo(_ingresoDespachoSimplExpo_declaracion,
		 * _ingresoDespachoSimplExpo_autenticacion);
		 * System.out.println("ingresoDespachoSimplExpo.result=" +
		 * _ingresoDespachoSimplExpo__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarManifiestoTitulo...");
		 * java.lang.String _consultarManifiestoTitulo_tipoMovimiento = "";
		 * java.lang.String _consultarManifiestoTitulo_numeroTitulo = "";
		 * java.lang.String _consultarManifiestoTitulo_prefijoTitulo = "";
		 * java.lang.String _consultarManifiestoTitulo_manifiesto = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarManifiestoTitulo_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestoTituloRespuestaConsulta
		 * _consultarManifiestoTitulo__return =
		 * port.consultarManifiestoTitulo(_consultarManifiestoTitulo_tipoMovimiento,
		 * _consultarManifiestoTitulo_numeroTitulo,
		 * _consultarManifiestoTitulo_prefijoTitulo,
		 * _consultarManifiestoTitulo_manifiesto,
		 * _consultarManifiestoTitulo_autenticacion);
		 * System.out.println("consultarManifiestoTitulo.result=" +
		 * _consultarManifiestoTitulo__return);
		 * 
		 * 
		 * } { System.out.println("Invoking trasladosEfc..."); java.lang.String
		 * _trasladosEfc_fechaDesde = ""; java.lang.String _trasladosEfc_fechaHasta =
		 * ""; java.lang.String _trasladosEfc_nroTraslado = "";
		 * py.gov.aduana.webservices.Autenticacion _trasladosEfc_autenticacion = null;
		 * py.gov.aduana.webservices.TrasladosRespuestaConsulta _trasladosEfc__return =
		 * port.trasladosEfc(_trasladosEfc_fechaDesde, _trasladosEfc_fechaHasta,
		 * _trasladosEfc_nroTraslado, _trasladosEfc_autenticacion);
		 * System.out.println("trasladosEfc.result=" + _trasladosEfc__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDesglosesIngAut...");
		 * java.lang.String _consultarDesglosesIngAut_fechaDesde = ""; java.lang.String
		 * _consultarDesglosesIngAut_fechaHasta = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarDesglosesIngAut_autenticacion = null;
		 * py.gov.aduana.webservices.DesgloseIngAutRespuestaConsulta
		 * _consultarDesglosesIngAut__return =
		 * port.consultarDesglosesIngAut(_consultarDesglosesIngAut_fechaDesde,
		 * _consultarDesglosesIngAut_fechaHasta,
		 * _consultarDesglosesIngAut_autenticacion);
		 * System.out.println("consultarDesglosesIngAut.result=" +
		 * _consultarDesglosesIngAut__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaDeclaracion...");
		 * java.lang.String _consultarListaDeclaracion_fechaIni = ""; java.lang.String
		 * _consultarListaDeclaracion_fechaFin = ""; java.lang.String
		 * _consultarListaDeclaracion_impExp = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaDeclaracion_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionListaRespuestaConsulta
		 * _consultarListaDeclaracion__return =
		 * port.consultarListaDeclaracion(_consultarListaDeclaracion_fechaIni,
		 * _consultarListaDeclaracion_fechaFin, _consultarListaDeclaracion_impExp,
		 * _consultarListaDeclaracion_autenticacion);
		 * System.out.println("consultarListaDeclaracion.result=" +
		 * _consultarListaDeclaracion__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultaIntervencionesLineas...");
		 * java.lang.String _consultaIntervencionesLineas_filtroIntervencion = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultaIntervencionesLineas_autenticacion = null;
		 * py.gov.aduana.webservices.ConsultaIntervencionesResp
		 * _consultaIntervencionesLineas__return = port.consultaIntervencionesLineas(
		 * _consultaIntervencionesLineas_filtroIntervencion,
		 * _consultaIntervencionesLineas_autenticacion);
		 * System.out.println("consultaIntervencionesLineas.result=" +
		 * _consultaIntervencionesLineas__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDeclaracionSinSalida...");
		 * java.lang.String _consultarDeclaracionSinSalida_despacho = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarDeclaracionSinSalida_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta
		 * _consultarDeclaracionSinSalida__return =
		 * port.consultarDeclaracionSinSalida(_consultarDeclaracionSinSalida_despacho,
		 * _consultarDeclaracionSinSalida_autenticacion);
		 * System.out.println("consultarDeclaracionSinSalida.result=" +
		 * _consultarDeclaracionSinSalida__return);
		 * 
		 * 
		 * } { System.out.println("Invoking actaRecepcion..."); java.lang.String
		 * _actaRecepcion_manifiesto = ""; py.gov.aduana.webservices.Autenticacion
		 * _actaRecepcion_autenticacion = null;
		 * py.gov.aduana.webservices.ActaRecepcionRespuestaConsulta
		 * _actaRecepcion__return = port.actaRecepcion(_actaRecepcion_manifiesto,
		 * _actaRecepcion_autenticacion); System.out.println("actaRecepcion.result=" +
		 * _actaRecepcion__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoDeposito...");
		 * py.gov.aduana.webservices.IdManifiesto _ingresoDeposito_idManifiesto = null;
		 * py.gov.aduana.webservices.Indicadores _ingresoDeposito_indicadores = null;
		 * java.util.List<py.gov.aduana.webservices.BultosAIngresar>
		 * _ingresoDeposito_bultosAIngresar = null; java.util.List<java.lang.String>
		 * _ingresoDeposito_contenedorAIngresar = null; java.lang.String
		 * _ingresoDeposito_idTransaccionDeposito = "";
		 * py.gov.aduana.webservices.Autenticacion _ingresoDeposito_autenticacion =
		 * null; py.gov.aduana.webservices.RespuestaTransaccion _ingresoDeposito__return
		 * = port.ingresoDeposito(_ingresoDeposito_idManifiesto,
		 * _ingresoDeposito_indicadores, _ingresoDeposito_bultosAIngresar,
		 * _ingresoDeposito_contenedorAIngresar, _ingresoDeposito_idTransaccionDeposito,
		 * _ingresoDeposito_autenticacion); System.out.println("ingresoDeposito.result="
		 * + _ingresoDeposito__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoEfc...");
		 * py.gov.aduana.webservices.TaiViaje _ingresoEfc_traslado = null;
		 * py.gov.aduana.webservices.Autenticacion _ingresoEfc_autenticacion = null;
		 * py.gov.aduana.webservices.TrasladoRespuestaConsulta _ingresoEfc__return =
		 * port.ingresoEfc(_ingresoEfc_traslado, _ingresoEfc_autenticacion);
		 * System.out.println("ingresoEfc.result=" + _ingresoEfc__return);
		 * 
		 * 
		 * } { System.out.println("Invoking expedienteTh..."); java.lang.String
		 * _expedienteTh_expediente = ""; py.gov.aduana.webservices.Autenticacion
		 * _expedienteTh_autenticacion = null;
		 * py.gov.aduana.webservices.ExpedienteThRespuestaConsulta _expedienteTh__return
		 * = port.expedienteTh(_expedienteTh_expediente, _expedienteTh_autenticacion);
		 * System.out.println("expedienteTh.result=" + _expedienteTh__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDeclaracionSimplLiquidacion...");
		 * java.lang.String
		 * _consultarDeclaracionSimplLiquidacion_idDeclaracionSimplificada = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarDeclaracionSimplLiquidacion_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta
		 * _consultarDeclaracionSimplLiquidacion__return =
		 * port.consultarDeclaracionSimplLiquidacion(
		 * _consultarDeclaracionSimplLiquidacion_idDeclaracionSimplificada,
		 * _consultarDeclaracionSimplLiquidacion_autenticacion);
		 * System.out.println("consultarDeclaracionSimplLiquidacion.result=" +
		 * _consultarDeclaracionSimplLiquidacion__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarManifiestosDeposito...");
		 * java.lang.String _consultarManifiestosDeposito_fechaDesde = "";
		 * java.lang.String _consultarManifiestosDeposito_fechaHasta = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarManifiestosDeposito_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestosTituloDepRespuestaConsulta
		 * _consultarManifiestosDeposito__return =
		 * port.consultarManifiestosDeposito(_consultarManifiestosDeposito_fechaDesde,
		 * _consultarManifiestosDeposito_fechaHasta,
		 * _consultarManifiestosDeposito_autenticacion);
		 * System.out.println("consultarManifiestosDeposito.result=" +
		 * _consultarManifiestosDeposito__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaDeclaracionLight...");
		 * java.lang.String _consultarListaDeclaracionLight_fechaIni = "";
		 * java.lang.String _consultarListaDeclaracionLight_fechaFin = "";
		 * java.lang.String _consultarListaDeclaracionLight_rucImportador = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaDeclaracionLight_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionListaRespuestaConsulta
		 * _consultarListaDeclaracionLight__return =
		 * port.consultarListaDeclaracionLight(_consultarListaDeclaracionLight_fechaIni,
		 * _consultarListaDeclaracionLight_fechaFin,
		 * _consultarListaDeclaracionLight_rucImportador,
		 * _consultarListaDeclaracionLight_autenticacion);
		 * System.out.println("consultarListaDeclaracionLight.result=" +
		 * _consultarListaDeclaracionLight__return);
		 * 
		 * 
		 * } { System.out.println("Invoking guiasSinOficializar...");
		 * py.gov.aduana.webservices.IdManifiesto _guiasSinOficializar_manifiesto =
		 * null; py.gov.aduana.webservices.Autenticacion
		 * _guiasSinOficializar_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestosTituloRespuestaConsulta
		 * _guiasSinOficializar__return =
		 * port.guiasSinOficializar(_guiasSinOficializar_manifiesto,
		 * _guiasSinOficializar_autenticacion);
		 * System.out.println("guiasSinOficializar.result=" +
		 * _guiasSinOficializar__return);
		 * 
		 * 
		 * } { System.out.println("Invoking crearBoletaCanon..."); java.lang.String
		 * _crearBoletaCanon_documento = ""; java.lang.String _crearBoletaCanon_tipo =
		 * ""; java.lang.String _crearBoletaCanon_monto = "";
		 * py.gov.aduana.webservices.Autenticacion _crearBoletaCanon_autenticacion =
		 * null; py.gov.aduana.webservices.BoletaCanonRespuesta
		 * _crearBoletaCanon__return =
		 * port.crearBoletaCanon(_crearBoletaCanon_documento, _crearBoletaCanon_tipo,
		 * _crearBoletaCanon_monto, _crearBoletaCanon_autenticacion);
		 * System.out.println("crearBoletaCanon.result=" + _crearBoletaCanon__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarTransporteInternacional...");
		 * java.lang.String _consultarTransporteInternacional_documento = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarTransporteInternacional_autenticacion = null;
		 * py.gov.aduana.webservices.TransporteInterRespuestaConsulta
		 * _consultarTransporteInternacional__return =
		 * port.consultarTransporteInternacional(
		 * _consultarTransporteInternacional_documento,
		 * _consultarTransporteInternacional_autenticacion);
		 * System.out.println("consultarTransporteInternacional.result=" +
		 * _consultarTransporteInternacional__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultaIntervenciones...");
		 * java.lang.String _consultaIntervenciones_filtroInicio = ""; java.lang.String
		 * _consultaIntervenciones_filtroFin = ""; java.lang.String
		 * _consultaIntervenciones_filtroPuerto = ""; java.lang.String
		 * _consultaIntervenciones_filtroAduana = ""; java.lang.String
		 * _consultaIntervenciones_filtroMatricula = ""; java.lang.String
		 * _consultaIntervenciones_filtroPlaca = ""; java.lang.String
		 * _consultaIntervenciones_filtroIntervencion = ""; java.lang.String
		 * _consultaIntervenciones_filtroConocimiento = "";
		 * py.gov.aduana.webservices.Autenticacion _consultaIntervenciones_autenticacion
		 * = null; py.gov.aduana.webservices.ConsultaIntervencionesResp
		 * _consultaIntervenciones__return =
		 * port.consultaIntervenciones(_consultaIntervenciones_filtroInicio,
		 * _consultaIntervenciones_filtroFin, _consultaIntervenciones_filtroPuerto,
		 * _consultaIntervenciones_filtroAduana,
		 * _consultaIntervenciones_filtroMatricula, _consultaIntervenciones_filtroPlaca,
		 * _consultaIntervenciones_filtroIntervencion,
		 * _consultaIntervenciones_filtroConocimiento,
		 * _consultaIntervenciones_autenticacion);
		 * System.out.println("consultaIntervenciones.result=" +
		 * _consultaIntervenciones__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultaIntervencionesContenedores...");
		 * java.lang.String _consultaIntervencionesContenedores_filtroIntervencion = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultaIntervencionesContenedores_autenticacion = null;
		 * py.gov.aduana.webservices.ConsultaIntervencionesResp
		 * _consultaIntervencionesContenedores__return =
		 * port.consultaIntervencionesContenedores(
		 * _consultaIntervencionesContenedores_filtroIntervencion,
		 * _consultaIntervencionesContenedores_autenticacion);
		 * System.out.println("consultaIntervencionesContenedores.result=" +
		 * _consultaIntervencionesContenedores__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoRemiEfcRegistrar...");
		 * java.lang.String _ingresoRemiEfcRegistrar_nroTimbrado = ""; java.lang.String
		 * _ingresoRemiEfcRegistrar_notaRemision = ""; java.lang.String
		 * _ingresoRemiEfcRegistrar_fechaIngreso = ""; java.lang.String
		 * _ingresoRemiEfcRegistrar_rucExportador = "";
		 * java.util.List<py.gov.aduana.webservices.DeclaracionEfc>
		 * _ingresoRemiEfcRegistrar_declaracionnes = null;
		 * py.gov.aduana.webservices.Autenticacion
		 * _ingresoRemiEfcRegistrar_autenticacion = null;
		 * py.gov.aduana.webservices.IngRemiEfcRespuesta
		 * _ingresoRemiEfcRegistrar__return =
		 * port.ingresoRemiEfcRegistrar(_ingresoRemiEfcRegistrar_nroTimbrado,
		 * _ingresoRemiEfcRegistrar_notaRemision, _ingresoRemiEfcRegistrar_fechaIngreso,
		 * _ingresoRemiEfcRegistrar_rucExportador,
		 * _ingresoRemiEfcRegistrar_declaracionnes,
		 * _ingresoRemiEfcRegistrar_autenticacion);
		 * System.out.println("ingresoRemiEfcRegistrar.result=" +
		 * _ingresoRemiEfcRegistrar__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaManifiesto...");
		 * java.lang.String _consultarListaManifiesto_fecha = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaManifiesto_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestoListaRespuestaConsulta
		 * _consultarListaManifiesto__return =
		 * port.consultarListaManifiesto(_consultarListaManifiesto_fecha,
		 * _consultarListaManifiesto_autenticacion);
		 * System.out.println("consultarListaManifiesto.result=" +
		 * _consultarListaManifiesto__return);
		 * 
		 * 
		 * }
		 * 
		 * { System.out.println("Invoking revertirDeposito...");
		 * py.gov.aduana.webservices.IdManifiesto _revertirDeposito_idManifiesto = null;
		 * py.gov.aduana.webservices.Autenticacion _revertirDeposito_autenticacion =
		 * null; py.gov.aduana.webservices.ManifiestoRespuestaConsulta
		 * _revertirDeposito__return =
		 * port.revertirDeposito(_revertirDeposito_idManifiesto,
		 * _revertirDeposito_autenticacion);
		 * System.out.println("revertirDeposito.result=" + _revertirDeposito__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarManifiestoTema...");
		 * py.gov.aduana.webservices.IdManifiesto _consultarManifiestoTema_idManifiesto
		 * = null; py.gov.aduana.webservices.Autenticacion
		 * _consultarManifiestoTema_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestoRespuestaConsulta
		 * _consultarManifiestoTema__return =
		 * port.consultarManifiestoTema(_consultarManifiestoTema_idManifiesto,
		 * _consultarManifiestoTema_autenticacion);
		 * System.out.println("consultarManifiestoTema.result=" +
		 * _consultarManifiestoTema__return);
		 * 
		 * 
		 * } { System.out.println("Invoking afectacionesCanon...");
		 * java.util.List<py.gov.aduana.webservices.AfectarCanon>
		 * _afectacionesCanon_afectaciones = null;
		 * py.gov.aduana.webservices.Autenticacion _afectacionesCanon_autenticacion =
		 * null; py.gov.aduana.webservices.AfectacionesCanonRespuesta
		 * _afectacionesCanon__return =
		 * port.afectacionesCanon(_afectacionesCanon_afectaciones,
		 * _afectacionesCanon_autenticacion);
		 * System.out.println("afectacionesCanon.result=" + _afectacionesCanon__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarCotizacion..."); java.lang.String
		 * _consultarCotizacion_fecha = ""; java.lang.String _consultarCotizacion_moneda
		 * = ""; py.gov.aduana.webservices.Autenticacion
		 * _consultarCotizacion_autenticacion = null;
		 * py.gov.aduana.webservices.CotizacionRespuestaConsulta
		 * _consultarCotizacion__return =
		 * port.consultarCotizacion(_consultarCotizacion_fecha,
		 * _consultarCotizacion_moneda, _consultarCotizacion_autenticacion);
		 * System.out.println("consultarCotizacion.result=" +
		 * _consultarCotizacion__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarCodigoBarra..."); java.lang.String
		 * _consultarCodigoBarra_burSource = ""; java.lang.String
		 * _consultarCodigoBarra_burTarget = ""; java.lang.String
		 * _consultarCodigoBarra_state = ""; java.lang.String
		 * _consultarCodigoBarra_nroctd = ""; java.lang.String
		 * _consultarCodigoBarra_operType = ""; java.lang.String
		 * _consultarCodigoBarra_idso = ""; java.lang.String _consultarCodigoBarra_mic =
		 * ""; java.lang.String _consultarCodigoBarra_boleta = ""; java.lang.String
		 * _consultarCodigoBarra_trsp = ""; java.lang.String
		 * _consultarCodigoBarra_dBegin = ""; java.lang.String
		 * _consultarCodigoBarra_dEnd = ""; py.gov.aduana.webservices.Autenticacion
		 * _consultarCodigoBarra_autenticacion = null;
		 * py.gov.aduana.webservices.CodigoBarraRespuestaConsulta
		 * _consultarCodigoBarra__return =
		 * port.consultarCodigoBarra(_consultarCodigoBarra_burSource,
		 * _consultarCodigoBarra_burTarget, _consultarCodigoBarra_state,
		 * _consultarCodigoBarra_nroctd, _consultarCodigoBarra_operType,
		 * _consultarCodigoBarra_idso, _consultarCodigoBarra_mic,
		 * _consultarCodigoBarra_boleta, _consultarCodigoBarra_trsp,
		 * _consultarCodigoBarra_dBegin, _consultarCodigoBarra_dEnd,
		 * _consultarCodigoBarra_autenticacion);
		 * System.out.println("consultarCodigoBarra.result=" +
		 * _consultarCodigoBarra__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaDecSimplPendGroup...");
		 * java.lang.String _consultarListaDecSimplPendGroup_fechaIni = "";
		 * java.lang.String _consultarListaDecSimplPendGroup_fechaFin = "";
		 * java.lang.String _consultarListaDecSimplPendGroup_ruc = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaDecSimplPendGroup_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta
		 * _consultarListaDecSimplPendGroup__return =
		 * port.consultarListaDecSimplPendGroup(
		 * _consultarListaDecSimplPendGroup_fechaIni,
		 * _consultarListaDecSimplPendGroup_fechaFin,
		 * _consultarListaDecSimplPendGroup_ruc,
		 * _consultarListaDecSimplPendGroup_autenticacion);
		 * System.out.println("consultarListaDecSimplPendGroup.result=" +
		 * _consultarListaDecSimplPendGroup__return);
		 * 
		 * 
		 * } { System.out.println("Invoking trasladoEfc..."); java.lang.String
		 * _trasladoEfc_nroTraslado = ""; py.gov.aduana.webservices.Autenticacion
		 * _trasladoEfc_autenticacion = null;
		 * py.gov.aduana.webservices.TrasladoRespuestaConsulta _trasladoEfc__return =
		 * port.trasladoEfc(_trasladoEfc_nroTraslado, _trasladoEfc_autenticacion);
		 * System.out.println("trasladoEfc.result=" + _trasladoEfc__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarGuiaMadre..."); java.lang.String
		 * _consultarGuiaMadre_manifiesto = ""; java.lang.String
		 * _consultarGuiaMadre_prefijo = ""; java.lang.String _consultarGuiaMadre_titulo
		 * = ""; py.gov.aduana.webservices.Autenticacion
		 * _consultarGuiaMadre_autenticacion = null;
		 * py.gov.aduana.webservices.GuiaMadreRespuestaConsulta
		 * _consultarGuiaMadre__return =
		 * port.consultarGuiaMadre(_consultarGuiaMadre_manifiesto,
		 * _consultarGuiaMadre_prefijo, _consultarGuiaMadre_titulo,
		 * _consultarGuiaMadre_autenticacion);
		 * System.out.println("consultarGuiaMadre.result=" +
		 * _consultarGuiaMadre__return);
		 * 
		 * 
		 * } { System.out.println("Invoking salidaZonaPrimaria...");
		 * py.gov.aduana.webservices.CabeceraSalida _salidaZonaPrimaria_cabeceraSalida =
		 * null; java.lang.String _salidaZonaPrimaria_idTransaccionDeposito = "";
		 * py.gov.aduana.webservices.Autenticacion _salidaZonaPrimaria_autenticacion =
		 * null; py.gov.aduana.webservices.RespuestaSalida _salidaZonaPrimaria__return =
		 * port.salidaZonaPrimaria(_salidaZonaPrimaria_cabeceraSalida,
		 * _salidaZonaPrimaria_idTransaccionDeposito,
		 * _salidaZonaPrimaria_autenticacion);
		 * System.out.println("salidaZonaPrimaria.result=" +
		 * _salidaZonaPrimaria__return);
		 * 
		 * 
		 * } { System.out.println("Invoking salidaZonaPrimariaRemate...");
		 * py.gov.aduana.webservices.CabeceraSalida
		 * _salidaZonaPrimariaRemate_cabeceraSalida = null; java.lang.String
		 * _salidaZonaPrimariaRemate_idTransaccionDeposito = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _salidaZonaPrimariaRemate_autenticacion = null;
		 * py.gov.aduana.webservices.RespuestaSalida _salidaZonaPrimariaRemate__return =
		 * port.salidaZonaPrimariaRemate(_salidaZonaPrimariaRemate_cabeceraSalida,
		 * _salidaZonaPrimariaRemate_idTransaccionDeposito,
		 * _salidaZonaPrimariaRemate_autenticacion);
		 * System.out.println("salidaZonaPrimariaRemate.result=" +
		 * _salidaZonaPrimariaRemate__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDesconsolidadosIngAut...");
		 * java.lang.String _consultarDesconsolidadosIngAut_fechaDesde = "";
		 * java.lang.String _consultarDesconsolidadosIngAut_fechaHasta = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarDesconsolidadosIngAut_autenticacion = null;
		 * py.gov.aduana.webservices.DesconsolidadoIngAutRespuestaConsulta
		 * _consultarDesconsolidadosIngAut__return =
		 * port.consultarDesconsolidadosIngAut(
		 * _consultarDesconsolidadosIngAut_fechaDesde,
		 * _consultarDesconsolidadosIngAut_fechaHasta,
		 * _consultarDesconsolidadosIngAut_autenticacion);
		 * System.out.println("consultarDesconsolidadosIngAut.result=" +
		 * _consultarDesconsolidadosIngAut__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoRemiExportador..."); java.lang.String
		 * _ingresoRemiExportador_rucExportador = "";
		 * py.gov.aduana.webservices.Autenticacion _ingresoRemiExportador_autenticacion
		 * = null; py.gov.aduana.webservices.IngRemiReferenciaExportadorRespuesta
		 * _ingresoRemiExportador__return =
		 * port.ingresoRemiExportador(_ingresoRemiExportador_rucExportador,
		 * _ingresoRemiExportador_autenticacion);
		 * System.out.println("ingresoRemiExportador.result=" +
		 * _ingresoRemiExportador__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaDecSimplLight...");
		 * java.lang.String _consultarListaDecSimplLight_fechaIni = ""; java.lang.String
		 * _consultarListaDecSimplLight_fechaFin = ""; java.lang.String
		 * _consultarListaDecSimplLight_ruc = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaDecSimplLight_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta
		 * _consultarListaDecSimplLight__return =
		 * port.consultarListaDecSimplLight(_consultarListaDecSimplLight_fechaIni,
		 * _consultarListaDecSimplLight_fechaFin, _consultarListaDecSimplLight_ruc,
		 * _consultarListaDecSimplLight_autenticacion);
		 * System.out.println("consultarListaDecSimplLight.result=" +
		 * _consultarListaDecSimplLight__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoNovedadesDeposito...");
		 * py.gov.aduana.webservices.IdManifiesto _ingresoNovedadesDeposito_idManifiesto
		 * = null; py.gov.aduana.webservices.Indicadores
		 * _ingresoNovedadesDeposito_indicadores = null;
		 * java.util.List<py.gov.aduana.webservices.BultosAIngresar>
		 * _ingresoNovedadesDeposito_bultosAIngresar = null;
		 * java.util.List<java.lang.String>
		 * _ingresoNovedadesDeposito_contenedorAIngresar = null; java.lang.String
		 * _ingresoNovedadesDeposito_idTransaccionDeposito = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _ingresoNovedadesDeposito_autenticacion = null;
		 * py.gov.aduana.webservices.RespuestaTransaccion
		 * _ingresoNovedadesDeposito__return =
		 * port.ingresoNovedadesDeposito(_ingresoNovedadesDeposito_idManifiesto,
		 * _ingresoNovedadesDeposito_indicadores,
		 * _ingresoNovedadesDeposito_bultosAIngresar,
		 * _ingresoNovedadesDeposito_contenedorAIngresar,
		 * _ingresoNovedadesDeposito_idTransaccionDeposito,
		 * _ingresoNovedadesDeposito_autenticacion);
		 * System.out.println("ingresoNovedadesDeposito.result=" +
		 * _ingresoNovedadesDeposito__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaDeclaracionSimpl...");
		 * java.lang.String _consultarListaDeclaracionSimpl_fechaIni = "";
		 * java.lang.String _consultarListaDeclaracionSimpl_fechaFin = "";
		 * java.lang.String _consultarListaDeclaracionSimpl_ruc = ""; java.lang.String
		 * _consultarListaDeclaracionSimpl_tere = ""; java.lang.String
		 * _consultarListaDeclaracionSimpl_despacho = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaDeclaracionSimpl_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaListaRespuestaConsulta
		 * _consultarListaDeclaracionSimpl__return =
		 * port.consultarListaDeclaracionSimpl(_consultarListaDeclaracionSimpl_fechaIni,
		 * _consultarListaDeclaracionSimpl_fechaFin,
		 * _consultarListaDeclaracionSimpl_ruc, _consultarListaDeclaracionSimpl_tere,
		 * _consultarListaDeclaracionSimpl_despacho,
		 * _consultarListaDeclaracionSimpl_autenticacion);
		 * System.out.println("consultarListaDeclaracionSimpl.result=" +
		 * _consultarListaDeclaracionSimpl__return);
		 * 
		 * 
		 * } { System.out.println("Invoking verificarDespachoTere..."); java.lang.String
		 * _verificarDespachoTere_tere = ""; java.lang.String
		 * _verificarDespachoTere_manifiesto = ""; java.lang.String
		 * _verificarDespachoTere_titulo = ""; py.gov.aduana.webservices.Autenticacion
		 * _verificarDespachoTere_autenticacion = null;
		 * py.gov.aduana.webservices.GuiasSinDespachoResponse
		 * _verificarDespachoTere__return =
		 * port.verificarDespachoTere(_verificarDespachoTere_tere,
		 * _verificarDespachoTere_manifiesto, _verificarDespachoTere_titulo,
		 * _verificarDespachoTere_autenticacion);
		 * System.out.println("verificarDespachoTere.result=" +
		 * _verificarDespachoTere__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarSolicitudesIngAut...");
		 * java.lang.String _consultarSolicitudesIngAut_fechaDesde = "";
		 * java.lang.String _consultarSolicitudesIngAut_fechaHasta = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarSolicitudesIngAut_autenticacion = null;
		 * py.gov.aduana.webservices.SolicitudIngAutRespuestaConsulta
		 * _consultarSolicitudesIngAut__return =
		 * port.consultarSolicitudesIngAut(_consultarSolicitudesIngAut_fechaDesde,
		 * _consultarSolicitudesIngAut_fechaHasta,
		 * _consultarSolicitudesIngAut_autenticacion);
		 * System.out.println("consultarSolicitudesIngAut.result=" +
		 * _consultarSolicitudesIngAut__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarAgente..."); java.lang.String
		 * _consultarAgente_documento = ""; py.gov.aduana.webservices.Autenticacion
		 * _consultarAgente_autenticacion = null;
		 * py.gov.aduana.webservices.AgenteRespuestaConsulta _consultarAgente__return =
		 * port.consultarAgente(_consultarAgente_documento,
		 * _consultarAgente_autenticacion); System.out.println("consultarAgente.result="
		 * + _consultarAgente__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDeclaracionSimplificadaAll...");
		 * java.lang.String
		 * _consultarDeclaracionSimplificadaAll_idDeclaracionSimplificada = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarDeclaracionSimplificadaAll_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionSimplificadaRespuestaConsulta
		 * _consultarDeclaracionSimplificadaAll__return =
		 * port.consultarDeclaracionSimplificadaAll(
		 * _consultarDeclaracionSimplificadaAll_idDeclaracionSimplificada,
		 * _consultarDeclaracionSimplificadaAll_autenticacion);
		 * System.out.println("consultarDeclaracionSimplificadaAll.result=" +
		 * _consultarDeclaracionSimplificadaAll__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarGuiasManifiestosPrevios...");
		 * java.lang.String _consultarGuiasManifiestosPrevios_identificador = "";
		 * java.lang.String _consultarGuiasManifiestosPrevios_estado = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarGuiasManifiestosPrevios_autenticacion = null;
		 * py.gov.aduana.webservices.GuiasManifiestosPreviosRespuestaConsulta
		 * _consultarGuiasManifiestosPrevios__return =
		 * port.consultarGuiasManifiestosPrevios(
		 * _consultarGuiasManifiestosPrevios_identificador,
		 * _consultarGuiasManifiestosPrevios_estado,
		 * _consultarGuiasManifiestosPrevios_autenticacion);
		 * System.out.println("consultarGuiasManifiestosPrevios.result=" +
		 * _consultarGuiasManifiestosPrevios__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDesglose...");
		 * py.gov.aduana.webservices.IdManifiesto _consultarDesglose_idManifiesto =
		 * null; py.gov.aduana.webservices.Autenticacion
		 * _consultarDesglose_autenticacion = null;
		 * py.gov.aduana.webservices.DesgloseRespuestaConsulta
		 * _consultarDesglose__return =
		 * port.consultarDesglose(_consultarDesglose_idManifiesto,
		 * _consultarDesglose_autenticacion);
		 * System.out.println("consultarDesglose.result=" + _consultarDesglose__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarManifiesto...");
		 * py.gov.aduana.webservices.IdManifiesto _consultarManifiesto_idManifiesto =
		 * null; py.gov.aduana.webservices.Autenticacion
		 * _consultarManifiesto_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestoRespuestaConsulta
		 * _consultarManifiesto__return =
		 * port.consultarManifiesto(_consultarManifiesto_idManifiesto,
		 * _consultarManifiesto_autenticacion);
		 * System.out.println("consultarManifiesto.result=" +
		 * _consultarManifiesto__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDeclaracionExpo...");
		 * java.lang.String _consultarDeclaracionExpo_despacho = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarDeclaracionExpo_autenticacion = null;
		 * py.gov.aduana.webservices.DeclaracionRespuestaConsulta
		 * _consultarDeclaracionExpo__return =
		 * port.consultarDeclaracionExpo(_consultarDeclaracionExpo_despacho,
		 * _consultarDeclaracionExpo_autenticacion);
		 * System.out.println("consultarDeclaracionExpo.result=" +
		 * _consultarDeclaracionExpo__return);
		 * 
		 * 
		 * } { System.out.println("Invoking listaSalidaZonaPrimaria...");
		 * java.util.List<py.gov.aduana.webservices.CabeceraSalida>
		 * _listaSalidaZonaPrimaria_cabeceraListaSalida = null;
		 * py.gov.aduana.webservices.Autenticacion
		 * _listaSalidaZonaPrimaria_autenticacion = null;
		 * py.gov.aduana.webservices.RespuestaListaSalida
		 * _listaSalidaZonaPrimaria__return =
		 * port.listaSalidaZonaPrimaria(_listaSalidaZonaPrimaria_cabeceraListaSalida,
		 * _listaSalidaZonaPrimaria_autenticacion);
		 * System.out.println("listaSalidaZonaPrimaria.result=" +
		 * _listaSalidaZonaPrimaria__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarBultosDeclarados...");
		 * java.lang.String _consultarBultosDeclarados_manifiesto = ""; java.lang.String
		 * _consultarBultosDeclarados_prefijo = ""; java.lang.String
		 * _consultarBultosDeclarados_titulo = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarBultosDeclarados_autenticacion = null;
		 * py.gov.aduana.webservices.BultosDeclaradosRespuestaConsulta
		 * _consultarBultosDeclarados__return =
		 * port.consultarBultosDeclarados(_consultarBultosDeclarados_manifiesto,
		 * _consultarBultosDeclarados_prefijo, _consultarBultosDeclarados_titulo,
		 * _consultarBultosDeclarados_autenticacion);
		 * System.out.println("consultarBultosDeclarados.result=" +
		 * _consultarBultosDeclarados__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarManifiestosPrevios...");
		 * java.lang.String _consultarManifiestosPrevios_fechaDesde = "";
		 * java.lang.String _consultarManifiestosPrevios_fechaHasta = "";
		 * java.lang.String _consultarManifiestosPrevios_vuelo = ""; java.lang.String
		 * _consultarManifiestosPrevios_compania = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarManifiestosPrevios_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestosPreviosRespuestaConsulta
		 * _consultarManifiestosPrevios__return =
		 * port.consultarManifiestosPrevios(_consultarManifiestosPrevios_fechaDesde,
		 * _consultarManifiestosPrevios_fechaHasta, _consultarManifiestosPrevios_vuelo,
		 * _consultarManifiestosPrevios_compania,
		 * _consultarManifiestosPrevios_autenticacion);
		 * System.out.println("consultarManifiestosPrevios.result=" +
		 * _consultarManifiestosPrevios__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarDeclaracion..."); java.lang.String
		 * _consultarDeclaracion_idDeclaracion = ""; java.lang.String
		 * _consultarDeclaracion_noRequiereIngreso = "";
		 * py.gov.aduana.webservices.Autenticacion _consultarDeclaracion_autenticacion =
		 * null; py.gov.aduana.webservices.DeclaracionRespuestaConsulta
		 * _consultarDeclaracion__return =
		 * port.consultarDeclaracion(_consultarDeclaracion_idDeclaracion,
		 * _consultarDeclaracion_noRequiereIngreso,
		 * _consultarDeclaracion_autenticacion);
		 * System.out.println("consultarDeclaracion.result=" +
		 * _consultarDeclaracion__return);
		 * 
		 * 
		 * } { System.out.println("Invoking consultarListaManifiestos...");
		 * java.lang.String _consultarListaManifiestos_numeroTitulo = "";
		 * java.lang.String _consultarListaManifiestos_prefijoTitulo = "";
		 * java.lang.String _consultarListaManifiestos_fechaDesde = ""; java.lang.String
		 * _consultarListaManifiestos_fechaHasta = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _consultarListaManifiestos_autenticacion = null;
		 * py.gov.aduana.webservices.ManifiestosTituloRespuestaConsulta
		 * _consultarListaManifiestos__return =
		 * port.consultarListaManifiestos(_consultarListaManifiestos_numeroTitulo,
		 * _consultarListaManifiestos_prefijoTitulo,
		 * _consultarListaManifiestos_fechaDesde, _consultarListaManifiestos_fechaHasta,
		 * _consultarListaManifiestos_autenticacion);
		 * System.out.println("consultarListaManifiestos.result=" +
		 * _consultarListaManifiestos__return);
		 * 
		 * 
		 * } { System.out.println("Invoking salidaDespachoSimplExpo...");
		 * py.gov.aduana.webservices.DeclaracionSimplificada
		 * _salidaDespachoSimplExpo_declaracion = null;
		 * py.gov.aduana.webservices.Autenticacion
		 * _salidaDespachoSimplExpo_autenticacion = null;
		 * py.gov.aduana.webservices.DespachoSimplTransaccion
		 * _salidaDespachoSimplExpo__return =
		 * port.salidaDespachoSimplExpo(_salidaDespachoSimplExpo_declaracion,
		 * _salidaDespachoSimplExpo_autenticacion);
		 * System.out.println("salidaDespachoSimplExpo.result=" +
		 * _salidaDespachoSimplExpo__return);
		 * 
		 * 
		 * } { System.out.println("Invoking transito..."); java.lang.String
		 * _transito_rut = ""; py.gov.aduana.webservices.Autenticacion
		 * _transito_autenticacion = null;
		 * py.gov.aduana.webservices.TransitoRespuestaConsulta _transito__return =
		 * port.transito(_transito_rut, _transito_autenticacion);
		 * System.out.println("transito.result=" + _transito__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoDepositoTema...");
		 * py.gov.aduana.webservices.IdManifiesto _ingresoDepositoTema_idManifiesto =
		 * null; py.gov.aduana.webservices.Indicadores _ingresoDepositoTema_indicadores
		 * = null; java.util.List<py.gov.aduana.webservices.BultosAIngresar>
		 * _ingresoDepositoTema_bultosAIngresar = null; java.util.List<java.lang.String>
		 * _ingresoDepositoTema_contenedorAIngresar = null; java.lang.String
		 * _ingresoDepositoTema_idTransaccionDeposito = "";
		 * py.gov.aduana.webservices.Autenticacion _ingresoDepositoTema_autenticacion =
		 * null; py.gov.aduana.webservices.RespuestaTransaccion
		 * _ingresoDepositoTema__return =
		 * port.ingresoDepositoTema(_ingresoDepositoTema_idManifiesto,
		 * _ingresoDepositoTema_indicadores, _ingresoDepositoTema_bultosAIngresar,
		 * _ingresoDepositoTema_contenedorAIngresar,
		 * _ingresoDepositoTema_idTransaccionDeposito,
		 * _ingresoDepositoTema_autenticacion);
		 * System.out.println("ingresoDepositoTema.result=" +
		 * _ingresoDepositoTema__return);
		 * 
		 * 
		 * } { System.out.println("Invoking ingresoDepositoDocTrans...");
		 * java.lang.String _ingresoDepositoDocTrans_nroTransito = "";
		 * py.gov.aduana.webservices.Autenticacion
		 * _ingresoDepositoDocTrans_autenticacion = null;
		 * py.gov.aduana.webservices.RespuestaTransaccion
		 * _ingresoDepositoDocTrans__return =
		 * port.ingresoDepositoDocTrans(_ingresoDepositoDocTrans_nroTransito,
		 * _ingresoDepositoDocTrans_autenticacion);
		 * System.out.println("ingresoDepositoDocTrans.result=" +
		 * _ingresoDepositoDocTrans__return);
		 * 
		 * 
		 * }
		 */

		System.exit(0);
	}

}
